import type { LocalizedText } from "../puzzles/schema";

/**
 * Static UI-frame strings (chrome that isn't owned by a puzzle), keyed by locale
 * like every other string. Drafted for the launch language set; unverified
 * locales are corrected on feedback. Anything missing falls back to English.
 */
export const UI: Record<string, LocalizedText> = {
  // An account is optional and buys exactly one thing, so the footer says that
  // rather than the old "no accounts, no tracking", which stopped being true
  // the day sign-in shipped. A promise a project has outgrown is worse than no
  // promise: it teaches people to discount the ones that still hold.
  footer: {
    en: "No tracking. An account only carries your reviews",
    fr: "Aucun suivi. Un compte ne transporte que vos révisions",
    es: "Sin rastreo. Una cuenta solo lleva tus repasos",
    pt: "Sem rastreamento. Uma conta só carrega as suas revisões",
    ja: "追跡なし。アカウントは復習だけを引き継ぎます",
    zh: "无追踪。账户只承载你的复习进度",
    ru: "Без слежки. Аккаунт хранит только ваши повторения",
    hi: "कोई ट्रैकिंग नहीं। खाता केवल आपके रिवीज़न रखता है",
    bn: "কোনো ট্র্যাকিং নেই। অ্যাকাউন্ট শুধু আপনার পুনরাবৃত্তি বহন করে",
    ar: "بلا تتبّع. الحساب يحمل مراجعاتك فقط",
  },
  // The header eyebrow. Confoundle stopped being a one-a-day game when the
  // whole set was opened up, so this replaces "Daily" rather than sitting
  // beside it: a course that still called itself daily would be lying about
  // its own shape. `daily` is kept below because the share card still dates a
  // single play.
  lessons: {
    en: "Lessons",
    fr: "Leçons",
    es: "Lecciones",
    pt: "Lições",
    ja: "レッスン",
    zh: "课程",
    ru: "Уроки",
    hi: "पाठ",
    bn: "পাঠ",
    ar: "دروس",
  },
  allLessons: {
    en: "All lessons",
    fr: "Toutes les leçons",
    es: "Todas las lecciones",
    pt: "Todas as lições",
    ja: "すべてのレッスン",
    zh: "全部课程",
    ru: "Все уроки",
    hi: "सभी पाठ",
    bn: "সব পাঠ",
    ar: "كل الدروس",
  },
  stateNew: {
    en: "New",
    fr: "Nouvelle",
    es: "Nueva",
    pt: "Nova",
    ja: "未学習",
    zh: "未学",
    ru: "Новый",
    hi: "नया",
    bn: "নতুন",
    ar: "جديد",
  },
  stateLearned: {
    en: "Learned",
    fr: "Apprise",
    es: "Aprendida",
    pt: "Aprendida",
    ja: "学習済み",
    zh: "已学",
    ru: "Изучено",
    hi: "सीखा",
    bn: "শেখা হয়েছে",
    ar: "مكتسب",
  },
  stateMastered: {
    en: "Mastered",
    fr: "Maîtrisée",
    es: "Dominada",
    pt: "Dominada",
    ja: "習得済み",
    zh: "已掌握",
    ru: "Освоено",
    hi: "महारत",
    bn: "আয়ত্ত",
    ar: "متقن",
  },
  reviewsDue: {
    en: "Reviews due",
    fr: "Révisions à faire",
    es: "Repasos pendientes",
    pt: "Revisões pendentes",
    ja: "復習の予定",
    zh: "待复习",
    ru: "Пора повторить",
    hi: "रिवीज़न बाकी",
    bn: "পুনরাবৃত্তি বাকি",
    ar: "مراجعات مستحقة",
  },
  reviewsBlurb: {
    en: "Can you still spot the traps?",
    fr: "Repérez-vous encore les pièges ?",
    es: "¿Sigues detectando las trampas?",
    pt: "Ainda consegue ver as armadilhas?",
    ja: "まだ罠を見抜けますか？",
    zh: "你还能看出陷阱吗？",
    ru: "Всё ещё замечаете ловушки?",
    hi: "क्या आप अब भी जाल पहचान सकते हैं?",
    bn: "আপনি কি এখনও ফাঁদ ধরতে পারেন?",
    ar: "هل ما زلت تكتشف الفخاخ؟",
  },
  pitch: {
    en: "Spot the flaw before it fools you.",
    fr: "Repérez la faille avant qu'elle ne vous piège.",
    es: "Detecta el fallo antes de que te engañe.",
    pt: "Descubra a falha antes que ela o engane.",
    ja: "騙される前に、その誤りを見抜く。",
    zh: "在被误导之前，先看出破绽。",
    ru: "Заметьте изъян раньше, чем он обманет вас.",
    hi: "गलती आपको बहकाए, उससे पहले पहचानें।",
    bn: "ভুলটি আপনাকে বিভ্রান্ত করার আগেই ধরুন।",
    ar: "اكتشف الخلل قبل أن يخدعك.",
  },
  startHere: {
    en: "Start here",
    fr: "Commencer ici",
    es: "Empieza aquí",
    pt: "Comece aqui",
    ja: "ここから始める",
    zh: "从这里开始",
    ru: "Начните здесь",
    hi: "यहाँ से शुरू करें",
    bn: "এখান থেকে শুরু করুন",
    ar: "ابدأ من هنا",
  },
  continueLabel: {
    en: "Continue",
    fr: "Continuer",
    es: "Continuar",
    pt: "Continuar",
    ja: "続ける",
    zh: "继续",
    ru: "Продолжить",
    hi: "जारी रखें",
    bn: "চালিয়ে যান",
    ar: "متابعة",
  },
  reviewsShort: {
    en: "Reviews",
    fr: "Révisions",
    es: "Repasos",
    pt: "Revisões",
    ja: "復習",
    zh: "复习",
    ru: "Повторения",
    hi: "रिवीज़न",
    bn: "পুনরাবৃত্তি",
    ar: "مراجعات",
  },
  // The ladder's own vocabulary, which is WaniKani's. "Burned" means learned for
  // good rather than anything on fire, so the translations say permanent or
  // engraved instead of translating the English metaphor literally.
  bucketApprentice: {
    en: "Apprentice",
    fr: "Apprenti",
    es: "Aprendiz",
    pt: "Aprendiz",
    ja: "見習い",
    zh: "学徒",
    ru: "Ученик",
    hi: "नौसिखिया",
    bn: "শিক্ষানবিশ",
    ar: "مبتدئ",
  },
  bucketGuru: {
    en: "Guru",
    fr: "Gourou",
    es: "Gurú",
    pt: "Guru",
    ja: "師範",
    zh: "熟练",
    ru: "Гуру",
    hi: "गुरु",
    bn: "গুরু",
    ar: "خبير",
  },
  bucketMaster: {
    en: "Master",
    fr: "Maître",
    es: "Maestro",
    pt: "Mestre",
    ja: "達人",
    zh: "大师",
    ru: "Мастер",
    hi: "निपुण",
    bn: "দক্ষ",
    ar: "بارع",
  },
  bucketEnlightened: {
    en: "Enlightened",
    fr: "Éclairé",
    es: "Iluminado",
    pt: "Iluminado",
    ja: "悟り",
    zh: "开悟",
    ru: "Просветлённый",
    hi: "प्रबुद्ध",
    bn: "আলোকিত",
    ar: "مستنير",
  },
  bucketBurned: {
    en: "Burned",
    fr: "Gravé",
    es: "Grabado",
    pt: "Gravado",
    ja: "完全習得",
    zh: "已烙印",
    ru: "Закреплено",
    hi: "पक्का",
    bn: "স্থায়ী",
    ar: "راسخ",
  },
  nextReviews: {
    en: "Next reviews",
    fr: "Prochaines révisions",
    es: "Próximos repasos",
    pt: "Próximas revisões",
    ja: "次の復習",
    zh: "接下来的复习",
    ru: "Ближайшие повторения",
    hi: "अगले रिवीज़न",
    bn: "পরবর্তী পুনরাবৃত্তি",
    ar: "المراجعات القادمة",
  },
  nothingScheduled: {
    en: "Nothing scheduled yet",
    fr: "Rien de programmé pour l'instant",
    es: "Nada programado todavía",
    pt: "Nada agendado ainda",
    ja: "まだ予定はありません",
    zh: "暂无安排",
    ru: "Пока ничего не запланировано",
    hi: "अभी कुछ निर्धारित नहीं",
    bn: "এখনো কিছু নির্ধারিত নেই",
    ar: "لا شيء مجدول بعد",
  },
  progress: {
    en: "Progress",
    fr: "Progression",
    es: "Progreso",
    pt: "Progresso",
    ja: "進捗",
    zh: "进度",
    ru: "Прогресс",
    hi: "प्रगति",
    bn: "অগ্রগতি",
    ar: "التقدم",
  },
  mastery: {
    en: "Mastery",
    fr: "Maîtrise",
    es: "Dominio",
    pt: "Domínio",
    ja: "習得度",
    zh: "掌握程度",
    ru: "Освоение",
    hi: "महारत",
    bn: "দক্ষতা",
    ar: "الإتقان",
  },
  calibration: {
    en: "Calibration",
    fr: "Calibrage",
    es: "Calibración",
    pt: "Calibração",
    ja: "自信の精度",
    zh: "自信校准",
    ru: "Калибровка",
    hi: "आत्मविश्वास अंशांकन",
    bn: "আত্মবিশ্বাস যাচাই",
    ar: "معايرة الثقة",
  },
  streak: {
    en: "Streak",
    fr: "Série",
    es: "Racha",
    pt: "Sequência",
    ja: "連続",
    zh: "连续天数",
    ru: "Серия",
    hi: "लगातार",
    bn: "ধারাবাহিক",
    ar: "سلسلة",
  },
  best: {
    en: "Best",
    fr: "Record",
    es: "Mejor",
    pt: "Melhor",
    ja: "最高",
    zh: "最佳",
    ru: "Рекорд",
    hi: "सर्वश्रेष्ठ",
    bn: "সেরা",
    ar: "الأفضل",
  },
  caught: {
    en: "Caught",
    fr: "Repérés",
    es: "Detectadas",
    pt: "Detectadas",
    ja: "見抜いた率",
    zh: "识破率",
    ru: "Замечено",
    hi: "पकड़े गए",
    bn: "ধরা পড়েছে",
    ar: "تم كشفها",
  },
  dueNow: {
    en: "Due now",
    fr: "À réviser",
    es: "Toca repasar",
    pt: "Rever agora",
    ja: "今すぐ復習",
    zh: "现在复习",
    ru: "Пора повторить",
    hi: "अभी रिवीज़न",
    bn: "এখনই পুনরাবৃত্তি",
    ar: "حان وقت المراجعة",
  },
  nothingLearnedYet: {
    en: "Play a lesson to start building your map.",
    fr: "Faites une leçon pour commencer votre carte.",
    es: "Haz una lección para empezar tu mapa.",
    pt: "Faça uma lição para começar o seu mapa.",
    ja: "レッスンを1つ終えると、ここに記録が残ります。",
    zh: "完成一节课，就会开始生成你的图谱。",
    ru: "Пройдите урок, чтобы начать свою карту.",
    hi: "अपना नक्शा बनाना शुरू करने के लिए एक पाठ करें।",
    bn: "আপনার মানচিত্র শুরু করতে একটি পাঠ করুন।",
    ar: "أكمل درسًا لتبدأ خريطتك.",
  },
  sureAndWrong: {
    en: "You were sure, and wrong",
    fr: "Vous étiez sûr, et vous aviez tort",
    es: "Estabas seguro, y te equivocaste",
    pt: "Estava certo disso, e errou",
    ja: "確信して、間違えた項目",
    zh: "你很确定，但答错了",
    ru: "Вы были уверены и ошиблись",
    hi: "आप निश्चित थे, और गलत थे",
    bn: "আপনি নিশ্চিত ছিলেন, এবং ভুল ছিলেন",
    ar: "كنت واثقًا، وكنت مخطئًا",
  },
  back: {
    en: "Back",
    fr: "Retour",
    es: "Volver",
    pt: "Voltar",
    ja: "戻る",
    zh: "返回",
    ru: "Назад",
    hi: "वापस",
    bn: "ফিরে যান",
    ar: "رجوع",
  },
  daily: {
    en: "Daily",
    fr: "Quotidien",
    es: "Diario",
    pt: "Diário",
    ja: "毎日",
    zh: "每日",
    ru: "Ежедневно",
    hi: "रोज़ाना",
    bn: "প্রতিদিন",
    ar: "يومي",
  },
  reasoning: {
    en: "reasoning",
    fr: "raisonnement",
    es: "razonamiento",
    pt: "raciocínio",
    ja: "推論",
    zh: "推理",
    ru: "рассуждение",
    hi: "तर्क",
    bn: "যুক্তি",
    ar: "تفكير منطقي",
  },
  playedToday: {
    en: "Played today",
    fr: "Joué aujourd'hui",
    es: "Jugado hoy",
    pt: "Jogado hoje",
    ja: "本日プレイ済み",
    zh: "今天已玩",
    ru: "Сыграно сегодня",
    hi: "आज खेला",
    bn: "আজ খেলা হয়েছে",
    ar: "لعبت اليوم",
  },
  language: {
    en: "Language",
    fr: "Langue",
    es: "Idioma",
    pt: "Idioma",
    ja: "言語",
    zh: "语言",
    ru: "Язык",
    hi: "भाषा",
    bn: "ভাষা",
    ar: "اللغة",
  },
};

/**
 * Account panel strings, kept apart from UI only because there are enough of
 * them to be worth their own block. Same rule applies: every locale filled in,
 * enforced by ui.test.ts rather than remembered.
 *
 * The wording is chosen to promise no more than the code does. "Your reviews
 * follow you" is the whole benefit; anything grander would be marketing, and
 * this is a project about not being fooled.
 */
/**
 * The "hand this to someone else" control on the lesson screen. Three strings,
 * kept here rather than inline so ui.test.ts holds them to the same locale
 * parity as everything else.
 */
export const LESSON_SHARE: Record<string, LocalizedText> = {
  blurb: {
    en: "Arguing with someone about this? Send them the explanation.",
    fr: "Vous en discutez avec quelqu'un ? Envoyez-lui l'explication.",
    es: "¿Lo estás discutiendo con alguien? Envíale la explicación.",
    pt: "A discutir isto com alguém? Envie-lhe a explicação.",
    ja: "この件で議論していますか。相手に解説を送れます。",
    zh: "正在和别人争论这个问题？把解释发给对方。",
    ru: "Спорите об этом с кем-то? Отправьте им объяснение.",
    hi: "इस पर किसी से बहस हो रही है? उन्हें समझाने वाला पेज भेजें।",
    bn: "এই নিয়ে কারও সঙ্গে তর্ক চলছে? তাঁকে ব্যাখ্যাটি পাঠান।",
    ar: "تناقش أحدهم في هذا؟ أرسل له الشرح.",
  },
  copy: {
    en: "Copy link",
    fr: "Copier le lien",
    es: "Copiar enlace",
    pt: "Copiar ligação",
    ja: "リンクをコピー",
    zh: "复制链接",
    ru: "Скопировать ссылку",
    hi: "लिंक कॉपी करें",
    bn: "লিঙ্ক কপি করুন",
    ar: "نسخ الرابط",
  },
  copied: {
    en: "Copied",
    fr: "Copié",
    es: "Copiado",
    pt: "Copiado",
    ja: "コピーしました",
    zh: "已复制",
    ru: "Скопировано",
    hi: "कॉपी हो गया",
    bn: "কপি হয়েছে",
    ar: "تم النسخ",
  },
};

export const ACCOUNT: Record<string, LocalizedText> = {
  signIn: {
    en: "Sign in",
    zh: "登录",
    hi: "साइन इन करें",
    es: "Iniciar sesión",
    fr: "Se connecter",
    ar: "تسجيل الدخول",
    bn: "সাইন ইন",
    pt: "Iniciar sessão",
    ru: "Войти",
    ja: "ログイン",
  },
  signedIn: {
    en: "Account",
    zh: "账户",
    hi: "अकाउंट",
    es: "Cuenta",
    fr: "Compte",
    ar: "الحساب",
    bn: "অ্যাকাউন্ট",
    pt: "Conta",
    ru: "Аккаунт",
    ja: "アカウント",
  },
  signedInAs: {
    en: "Signed in as",
    zh: "已登录为",
    hi: "साइन इन किया हुआ अकाउंट",
    es: "Sesión iniciada como",
    fr: "Connecté en tant que",
    ar: "مسجّل الدخول باسم",
    bn: "সাইন ইন করেছেন",
    pt: "Sessão iniciada como",
    ru: "Вы вошли как",
    ja: "ログイン中のアカウント",
  },
  blurb: {
    en: "Optional. An account carries your review schedule between devices, and nothing else.",
    zh: "可选。账户只用于在设备之间同步你的复习计划，不做别的。",
    hi: "वैकल्पिक। अकाउंट आपके रिवीजन शेड्यूल को एक डिवाइस से दूसरे तक ले जाता है, इसके अलावा कुछ नहीं।",
    es: "Opcional. Una cuenta traslada tu calendario de repasos entre dispositivos, y nada más.",
    fr: "Facultatif. Un compte transporte votre programme de révisions d'un appareil à l'autre, et rien de plus.",
    ar: "اختياري. الحساب ينقل جدول مراجعاتك بين أجهزتك، ولا شيء غير ذلك.",
    bn: "ঐচ্ছিক। অ্যাকাউন্ট শুধু আপনার রিভিশনের সময়সূচি এক ডিভাইস থেকে আরেক ডিভাইসে নিয়ে যায়, আর কিছুই নয়।",
    pt: "Opcional. Uma conta leva o teu plano de revisões de um dispositivo para outro, e nada mais.",
    ru: "Необязательно. Аккаунт переносит расписание повторений между устройствами, и больше ничего.",
    ja: "任意です。アカウントは復習スケジュールを端末間で引き継ぐためだけのもので、それ以外には使いません。",
  },
  or: {
    en: "or",
    zh: "或",
    hi: "या",
    es: "o",
    fr: "ou",
    ar: "أو",
    bn: "অথবা",
    pt: "ou",
    ru: "или",
    ja: "または",
  },
  emailLabel: {
    en: "Email address",
    zh: "邮箱地址",
    hi: "ईमेल पता",
    es: "Correo electrónico",
    fr: "Adresse e-mail",
    ar: "البريد الإلكتروني",
    bn: "ইমেইল ঠিকানা",
    pt: "Endereço de email",
    ru: "Электронная почта",
    ja: "メールアドレス",
  },
  emailPlaceholder: {
    en: "you@example.com",
    zh: "you@example.com",
    hi: "you@example.com",
    es: "tu@ejemplo.com",
    fr: "vous@exemple.com",
    ar: "you@example.com",
    bn: "you@example.com",
    pt: "voce@exemplo.com",
    ru: "you@example.com",
    ja: "you@example.com",
  },
  sendCode: {
    en: "Email me a code",
    zh: "发送验证码",
    hi: "मुझे कोड ईमेल करें",
    es: "Enviarme un código",
    fr: "Recevoir un code",
    ar: "أرسل لي رمزًا بالبريد",
    bn: "ইমেইলে কোড পাঠান",
    pt: "Enviar-me um código",
    ru: "Прислать код",
    ja: "コードをメールで送信",
  },
  codeSent: {
    en: "Check your inbox. The code works once and lasts ten minutes.",
    zh: "请查收邮件。验证码只能使用一次，十分钟内有效。",
    hi: "अपना इनबॉक्स देखें। कोड एक ही बार काम करता है और दस मिनट तक चलता है।",
    es: "Revisa tu bandeja de entrada. El código sirve una sola vez y dura diez minutos.",
    fr: "Regardez votre boîte de réception. Le code sert une seule fois et vaut dix minutes.",
    ar: "تفقّد بريدك الوارد. الرمز يعمل مرة واحدة وتنتهي صلاحيته بعد عشر دقائق.",
    bn: "ইনবক্স দেখুন। কোডটি একবারই কাজ করে এবং দশ মিনিট পর্যন্ত বৈধ থাকে।",
    pt: "Vê a tua caixa de entrada. O código serve uma vez e dura dez minutos.",
    ru: "Проверьте почту. Код действует десять минут и только один раз.",
    ja: "受信トレイをご確認ください。コードは1回のみ有効で、10分で失効します。",
  },
  codeLabel: {
    en: "Sign-in code",
    zh: "登录验证码",
    hi: "साइन इन कोड",
    es: "Código de acceso",
    fr: "Code de connexion",
    ar: "رمز تسجيل الدخول",
    bn: "সাইন ইন কোড",
    pt: "Código de acesso",
    ru: "Код входа",
    ja: "ログインコード",
  },
  codePlaceholder: {
    en: "6-digit code",
    zh: "6位验证码",
    hi: "6 अंकों का कोड",
    es: "Código de 6 dígitos",
    fr: "Code à 6 chiffres",
    ar: "رمز من ستة أرقام",
    bn: "৬ সংখ্যার কোড",
    pt: "Código de 6 dígitos",
    ru: "Код из 6 цифр",
    ja: "6桁のコード",
  },
  confirm: {
    en: "Confirm",
    zh: "确认",
    hi: "पुष्टि करें",
    es: "Confirmar",
    fr: "Confirmer",
    ar: "تأكيد",
    bn: "নিশ্চিত করুন",
    pt: "Confirmar",
    ru: "Подтвердить",
    ja: "確認",
  },
  inSync: {
    en: "{n} skills in sync",
    zh: "已同步 {n} 项技能",
    hi: "{n} स्किल सिंक में हैं",
    es: "{n} habilidades sincronizadas",
    fr: "{n} compétences synchronisées",
    ar: "المهارات المتزامنة: {n}",
    bn: "{n}টি দক্ষতা সিঙ্ক করা আছে",
    pt: "{n} competências sincronizadas",
    ru: "Синхронизировано навыков: {n}",
    ja: "{n}件のスキルを同期済み",
  },
  download: {
    en: "Download my data",
    zh: "下载我的数据",
    hi: "मेरा डेटा डाउनलोड करें",
    es: "Descargar mis datos",
    fr: "Télécharger mes données",
    ar: "تنزيل بياناتي",
    bn: "আমার ডেটা ডাউনলোড করুন",
    pt: "Descarregar os meus dados",
    ru: "Скачать мои данные",
    ja: "データをダウンロード",
  },
  signOut: {
    en: "Sign out",
    zh: "退出登录",
    hi: "साइन आउट करें",
    es: "Cerrar sesión",
    fr: "Se déconnecter",
    ar: "تسجيل الخروج",
    bn: "সাইন আউট",
    pt: "Terminar sessão",
    ru: "Выйти",
    ja: "ログアウト",
  },
  delete: {
    en: "Delete my account",
    zh: "删除我的账户",
    hi: "मेरा अकाउंट डिलीट करें",
    es: "Eliminar mi cuenta",
    fr: "Supprimer mon compte",
    ar: "حذف حسابي",
    bn: "অ্যাকাউন্ট মুছে ফেলুন",
    pt: "Eliminar a minha conta",
    ru: "Удалить аккаунт",
    ja: "アカウントを削除",
  },
  deleteWarning: {
    en: "This erases your account and every review it holds, on the server and on this device, immediately. There is no undo and no grace period.",
    zh: "此操作会立即删除你的账户，以及其中的全部复习记录，服务器上和本设备上的都会删除。无法撤销，也没有缓冲期。",
    hi: "इससे आपका अकाउंट और उसमें मौजूद हर रिवीजन, सर्वर पर और इस डिवाइस पर, तुरंत मिट जाता है। यह वापस नहीं लिया जा सकता और कोई मोहलत अवधि नहीं है।",
    es: "Esto borra tu cuenta y todos los repasos que contiene, en el servidor y en este dispositivo, de inmediato. No se puede deshacer y no hay periodo de gracia.",
    fr: "Cela efface immédiatement votre compte et toutes les révisions qu'il contient, sur le serveur et sur cet appareil. Il n'y a aucun retour en arrière et aucun délai de grâce.",
    ar: "هذا يمحو حسابك وكل مراجعة يحتوي عليها، على الخادم وعلى هذا الجهاز، فورًا. لا يمكن التراجع عن ذلك ولا توجد مهلة سماح.",
    bn: "এটি আপনার অ্যাকাউন্ট এবং তাতে থাকা প্রতিটি রিভিশন সার্ভারে ও এই ডিভাইসে সঙ্গে সঙ্গে মুছে ফেলে। এটি ফিরিয়ে আনার কোনো উপায় নেই, এবং অপেক্ষার কোনো সময়ও দেওয়া হয় না।",
    pt: "Isto apaga a tua conta e todas as revisões que ela contém, no servidor e neste dispositivo, de imediato. Não há como anular nem período de espera.",
    ru: "Это немедленно удалит ваш аккаунт и все хранящиеся в нём повторения, и на сервере, и на этом устройстве. Отменить действие нельзя, отсрочки нет.",
    ja: "アカウントと、そこに保存されているすべての復習記録を、サーバー上とこの端末上の両方から直ちに消去します。取り消しはできず、猶予期間もありません。",
  },
  deleteYes: {
    en: "Yes, erase everything",
    zh: "是，全部删除",
    hi: "हाँ, सब कुछ मिटा दें",
    es: "Sí, borrarlo todo",
    fr: "Oui, tout effacer",
    ar: "نعم، امحُ كل شيء",
    bn: "হ্যাঁ, সব মুছে ফেলুন",
    pt: "Sim, apagar tudo",
    ru: "Да, удалить всё",
    ja: "はい、すべて消去します",
  },
  cancel: {
    en: "Keep my account",
    zh: "保留我的账户",
    hi: "मेरा अकाउंट रहने दें",
    es: "Conservar mi cuenta",
    fr: "Garder mon compte",
    ar: "الاحتفاظ بحسابي",
    bn: "অ্যাকাউন্ট রেখে দিন",
    pt: "Manter a conta",
    ru: "Оставить аккаунт",
    ja: "アカウントを残す",
  },
  privacyNote: {
    en: "We store your email address and your review schedule. Nothing else.",
    zh: "我们只保存你的邮箱地址和复习计划，不保存其他内容。",
    hi: "हम आपका ईमेल पता और आपका रिवीजन शेड्यूल स्टोर करते हैं। इसके अलावा कुछ नहीं।",
    es: "Guardamos tu correo electrónico y tu calendario de repasos. Nada más.",
    fr: "Nous conservons votre adresse e-mail et votre programme de révisions. Rien d'autre.",
    ar: "نخزّن بريدك الإلكتروني وجدول مراجعاتك. لا شيء غير ذلك.",
    bn: "আমরা আপনার ইমেইল ঠিকানা এবং রিভিশনের সময়সূচি সংরক্ষণ করি। আর কিছুই নয়।",
    pt: "Guardamos o teu endereço de email e o teu plano de revisões. Nada mais.",
    ru: "Мы храним ваш адрес почты и расписание повторений. Больше ничего.",
    ja: "保存するのはメールアドレスと復習スケジュールのみです。それ以外は保存しません。",
  },
  privacyLink: {
    en: "What we store, and why",
    zh: "我们保存什么，为什么保存",
    hi: "हम क्या स्टोर करते हैं, और क्यों",
    es: "Qué guardamos, y por qué",
    fr: "Ce que nous conservons, et pourquoi",
    ar: "ما الذي نخزّنه ولماذا",
    bn: "আমরা কী সংরক্ষণ করি, এবং কেন",
    pt: "O que guardamos, e porquê",
    ru: "Что мы храним и зачем",
    ja: "保存する情報とその理由",
  },
  errNetwork: {
    en: "No connection. Try again.",
    zh: "无网络连接，请重试。",
    hi: "कनेक्शन नहीं है। फिर कोशिश करें।",
    es: "Sin conexión. Inténtalo de nuevo.",
    fr: "Pas de connexion. Réessayez.",
    ar: "لا يوجد اتصال. حاول مرة أخرى.",
    bn: "সংযোগ নেই। আবার চেষ্টা করুন।",
    pt: "Sem ligação. Tenta de novo.",
    ru: "Нет соединения. Попробуйте снова.",
    ja: "接続できません。もう一度お試しください。",
  },
  errBadEmail: {
    en: "That does not look like an email address.",
    zh: "这看起来不像是邮箱地址。",
    hi: "यह ईमेल पता नहीं लगता।",
    es: "Eso no parece un correo electrónico.",
    fr: "Cela ne ressemble pas à une adresse e-mail.",
    ar: "هذا لا يبدو بريدًا إلكترونيًا.",
    bn: "এটি ইমেইল ঠিকানা বলে মনে হচ্ছে না।",
    pt: "Isto não parece um endereço de email.",
    ru: "Это не похоже на адрес электронной почты.",
    ja: "メールアドレスの形式が正しくないようです。",
  },
  errBadCode: {
    en: "That code is not right.",
    zh: "验证码不正确。",
    hi: "यह कोड सही नहीं है।",
    es: "Ese código no es correcto.",
    fr: "Ce code n'est pas le bon.",
    ar: "هذا الرمز غير صحيح.",
    bn: "কোডটি ঠিক নয়।",
    pt: "Esse código não está correto.",
    ru: "Код неверный.",
    ja: "コードが正しくありません。",
  },
  errTooManyAttempts: {
    en: "Too many tries. Ask for a new code.",
    zh: "尝试次数过多，请重新获取验证码。",
    hi: "बहुत ज़्यादा कोशिशें। नया कोड मंगाएँ।",
    es: "Demasiados intentos. Pide un código nuevo.",
    fr: "Trop de tentatives. Demandez un nouveau code.",
    ar: "محاولات كثيرة. اطلب رمزًا جديدًا.",
    bn: "অনেকবার চেষ্টা করা হয়েছে। নতুন কোড নিন।",
    pt: "Demasiadas tentativas. Pede um código novo.",
    ru: "Слишком много попыток. Запросите новый код.",
    ja: "試行回数が多すぎます。新しいコードを取得してください。",
  },
  errTooManyRequests: {
    en: "Too many requests. Try again later.",
    zh: "请求过于频繁，请稍后再试。",
    hi: "बहुत ज़्यादा अनुरोध। बाद में कोशिश करें।",
    es: "Demasiadas solicitudes. Inténtalo más tarde.",
    fr: "Trop de requêtes. Réessayez plus tard.",
    ar: "طلبات كثيرة. حاول لاحقًا.",
    bn: "অনেক বেশি অনুরোধ। পরে আবার চেষ্টা করুন।",
    pt: "Demasiados pedidos. Tenta mais tarde.",
    ru: "Слишком много запросов. Попробуйте позже.",
    ja: "リクエストが多すぎます。しばらくしてからお試しください。",
  },
  errCodeJustSent: {
    en: "A code just went out. Give it a minute.",
    zh: "验证码刚刚发出，请稍等一分钟。",
    hi: "कोड अभी भेजा गया है। एक मिनट रुकें।",
    es: "Acabamos de enviar un código. Espera un minuto.",
    fr: "Un code vient de partir. Patientez une minute.",
    ar: "أُرسل رمز للتو. انتظر دقيقة.",
    bn: "একটি কোড এইমাত্র পাঠানো হয়েছে। এক মিনিট অপেক্ষা করুন।",
    pt: "Acabou de sair um código. Aguarda um minuto.",
    ru: "Код только что отправлен. Подождите минуту.",
    ja: "コードを送信したばかりです。少しお待ちください。",
  },
  errEmailLinked: {
    en: "That address already belongs to a different Google account.",
    zh: "该地址已属于另一个 Google 账户。",
    hi: "यह पता पहले से किसी दूसरे Google अकाउंट का है।",
    es: "Esa dirección ya pertenece a otra cuenta de Google.",
    fr: "Cette adresse appartient déjà à un autre compte Google.",
    ar: "هذا العنوان مرتبط بحساب Google آخر.",
    bn: "এই ঠিকানাটি অন্য একটি Google অ্যাকাউন্টের সঙ্গে যুক্ত।",
    pt: "Esse endereço já pertence a outra conta Google.",
    ru: "Этот адрес уже привязан к другому аккаунту Google.",
    ja: "このアドレスは別のGoogleアカウントに登録されています。",
  },
  errEmailUnavailable: {
    en: "Email sign-in is not set up here.",
    zh: "此处未启用邮箱登录。",
    hi: "यहाँ ईमेल से साइन इन उपलब्ध नहीं है।",
    es: "El inicio de sesión por correo no está configurado aquí.",
    fr: "La connexion par e-mail n'est pas disponible ici.",
    ar: "تسجيل الدخول بالبريد غير مُفعّل هنا.",
    bn: "এখানে ইমেইল দিয়ে সাইন ইন চালু নেই।",
    pt: "O acesso por email não está configurado aqui.",
    ru: "Вход по почте здесь не настроен.",
    ja: "メールでのログインはご利用いただけません。",
  },
  errGoogleBlocked: {
    en: "Google sign-in could not load. Use the email option instead.",
    zh: "Google 登录无法加载，请改用邮箱方式。",
    hi: "Google साइन इन लोड नहीं हो सका। इसके बजाय ईमेल विकल्प चुनें।",
    es: "No se pudo cargar el acceso con Google. Usa la opción de correo.",
    fr: "La connexion Google n'a pas pu se charger. Utilisez plutôt l'e-mail.",
    ar: "تعذّر تحميل تسجيل الدخول عبر Google. استخدم خيار البريد.",
    bn: "Google সাইন ইন লোড করা যায়নি। এর বদলে ইমেইল ব্যবহার করুন।",
    pt: "Não foi possível carregar o acesso Google. Usa a opção de email.",
    ru: "Вход через Google не загрузился. Воспользуйтесь входом по почте.",
    ja: "Googleログインを読み込めませんでした。メールでのログインをご利用ください。",
  },
  errGeneric: {
    en: "Something went wrong. Try again.",
    zh: "出了点问题，请重试。",
    hi: "कुछ गड़बड़ हो गई। फिर कोशिश करें।",
    es: "Algo salió mal. Inténtalo de nuevo.",
    fr: "Une erreur est survenue. Réessayez.",
    ar: "حدث خطأ ما. حاول مرة أخرى.",
    bn: "কিছু একটা ভুল হয়েছে। আবার চেষ্টা করুন।",
    pt: "Algo correu mal. Tenta de novo.",
    ru: "Что-то пошло не так. Попробуйте снова.",
    ja: "問題が発生しました。もう一度お試しください。",
  },
};
