import type { LocalizedText } from "../puzzles/schema";

/**
 * Static UI-frame strings (chrome that isn't owned by a puzzle), keyed by locale
 * like every other string. Drafted for the launch language set; unverified
 * locales are corrected on feedback. Anything missing falls back to English.
 */
export const UI: Record<string, LocalizedText> = {
  // An account is optional and buys exactly one thing, so the footer says that
  // rather than the old "no accounts, no tracking", which stopped being true
  // the day sign-in shipped. A promise a project has outgrown is worse than no
  // promise: it teaches people to discount the ones that still hold.
  footer: {
    en: "No tracking. An account only carries your reviews",
    fr: "Aucun suivi. Un compte ne transporte que vos révisions",
    es: "Sin rastreo. Una cuenta solo lleva tus repasos",
    pt: "Sem rastreamento. Uma conta só carrega as suas revisões",
    ja: "追跡なし。アカウントは復習だけを引き継ぎます",
    zh: "无追踪。账户只承载你的复习进度",
    ru: "Без слежки. Аккаунт хранит только ваши повторения",
    hi: "कोई ट्रैकिंग नहीं। खाता केवल आपके रिवीज़न रखता है",
    bn: "কোনো ট্র্যাকিং নেই। অ্যাকাউন্ট শুধু আপনার পুনরাবৃত্তি বহন করে",
    ar: "بلا تتبّع. الحساب يحمل مراجعاتك فقط",
  },
  // The header eyebrow. Confoundle stopped being a one-a-day game when the
  // whole set was opened up, so this replaces "Daily" rather than sitting
  // beside it: a course that still called itself daily would be lying about
  // its own shape. `daily` is kept below because the share card still dates a
  // single play.
  lessons: {
    en: "Lessons",
    fr: "Leçons",
    es: "Lecciones",
    pt: "Lições",
    ja: "レッスン",
    zh: "课程",
    ru: "Уроки",
    hi: "पाठ",
    bn: "পাঠ",
    ar: "دروس",
  },
  allLessons: {
    en: "All lessons",
    fr: "Toutes les leçons",
    es: "Todas las lecciones",
    pt: "Todas as lições",
    ja: "すべてのレッスン",
    zh: "全部课程",
    ru: "Все уроки",
    hi: "सभी पाठ",
    bn: "সব পাঠ",
    ar: "كل الدروس",
  },
  stateNew: {
    en: "New",
    fr: "Nouvelle",
    es: "Nueva",
    pt: "Nova",
    ja: "未学習",
    zh: "未学",
    ru: "Новый",
    hi: "नया",
    bn: "নতুন",
    ar: "جديد",
  },
  stateLearned: {
    en: "Learned",
    fr: "Apprise",
    es: "Aprendida",
    pt: "Aprendida",
    ja: "学習済み",
    zh: "已学",
    ru: "Изучено",
    hi: "सीखा",
    bn: "শেখা হয়েছে",
    ar: "مكتسب",
  },
  stateMastered: {
    en: "Mastered",
    fr: "Maîtrisée",
    es: "Dominada",
    pt: "Dominada",
    ja: "習得済み",
    zh: "已掌握",
    ru: "Освоено",
    hi: "महारत",
    bn: "আয়ত্ত",
    ar: "متقن",
  },
  reviewsDue: {
    en: "Reviews due",
    fr: "Révisions à faire",
    es: "Repasos pendientes",
    pt: "Revisões pendentes",
    ja: "復習の予定",
    zh: "待复习",
    ru: "Пора повторить",
    hi: "रिवीज़न बाकी",
    bn: "পুনরাবৃত্তি বাকি",
    ar: "مراجعات مستحقة",
  },
  reviewsBlurb: {
    en: "Can you still spot the traps?",
    fr: "Repérez-vous encore les pièges ?",
    es: "¿Sigues detectando las trampas?",
    pt: "Ainda consegue ver as armadilhas?",
    ja: "まだ罠を見抜けますか？",
    zh: "你还能看出陷阱吗？",
    ru: "Всё ещё замечаете ловушки?",
    hi: "क्या आप अब भी जाल पहचान सकते हैं?",
    bn: "আপনি কি এখনও ফাঁদ ধরতে পারেন?",
    ar: "هل ما زلت تكتشف الفخاخ؟",
  },
  pitch: {
    en: "Spot the flaw before it fools you.",
    fr: "Repérez la faille avant qu'elle ne vous piège.",
    es: "Detecta el fallo antes de que te engañe.",
    pt: "Descubra a falha antes que ela o engane.",
    ja: "騙される前に、その誤りを見抜く。",
    zh: "在被误导之前，先看出破绽。",
    ru: "Заметьте изъян раньше, чем он обманет вас.",
    hi: "गलती आपको बहकाए, उससे पहले पहचानें।",
    bn: "ভুলটি আপনাকে বিভ্রান্ত করার আগেই ধরুন।",
    ar: "اكتشف الخلل قبل أن يخدعك.",
  },
  startHere: {
    en: "Start here",
    fr: "Commencer ici",
    es: "Empieza aquí",
    pt: "Comece aqui",
    ja: "ここから始める",
    zh: "从这里开始",
    ru: "Начните здесь",
    hi: "यहाँ से शुरू करें",
    bn: "এখান থেকে শুরু করুন",
    ar: "ابدأ من هنا",
  },
  continueLabel: {
    en: "Continue",
    fr: "Continuer",
    es: "Continuar",
    pt: "Continuar",
    ja: "続ける",
    zh: "继续",
    ru: "Продолжить",
    hi: "जारी रखें",
    bn: "চালিয়ে যান",
    ar: "متابعة",
  },
  reviewsShort: {
    en: "Reviews",
    fr: "Révisions",
    es: "Repasos",
    pt: "Revisões",
    ja: "復習",
    zh: "复习",
    ru: "Повторения",
    hi: "रिवीज़न",
    bn: "পুনরাবৃত্তি",
    ar: "مراجعات",
  },
  // The ladder's own vocabulary, which is WaniKani's. "Burned" means learned for
  // good rather than anything on fire, so the translations say permanent or
  // engraved instead of translating the English metaphor literally.
  bucketApprentice: {
    en: "Apprentice",
    fr: "Apprenti",
    es: "Aprendiz",
    pt: "Aprendiz",
    ja: "見習い",
    zh: "学徒",
    ru: "Ученик",
    hi: "नौसिखिया",
    bn: "শিক্ষানবিশ",
    ar: "مبتدئ",
  },
  bucketGuru: {
    en: "Guru",
    fr: "Gourou",
    es: "Gurú",
    pt: "Guru",
    ja: "師範",
    zh: "熟练",
    ru: "Гуру",
    hi: "गुरु",
    bn: "গুরু",
    ar: "خبير",
  },
  bucketMaster: {
    en: "Master",
    fr: "Maître",
    es: "Maestro",
    pt: "Mestre",
    ja: "達人",
    zh: "大师",
    ru: "Мастер",
    hi: "निपुण",
    bn: "দক্ষ",
    ar: "بارع",
  },
  bucketEnlightened: {
    en: "Enlightened",
    fr: "Éclairé",
    es: "Iluminado",
    pt: "Iluminado",
    ja: "悟り",
    zh: "开悟",
    ru: "Просветлённый",
    hi: "प्रबुद्ध",
    bn: "আলোকিত",
    ar: "مستنير",
  },
  bucketBurned: {
    en: "Burned",
    fr: "Gravé",
    es: "Grabado",
    pt: "Gravado",
    ja: "完全習得",
    zh: "已烙印",
    ru: "Закреплено",
    hi: "पक्का",
    bn: "স্থায়ী",
    ar: "راسخ",
  },
  practise: {
    en: "Practise anyway",
    fr: "S'entraîner quand même",
    es: "Practicar igualmente",
    pt: "Praticar mesmo assim",
    ja: "それでも練習する",
    zh: "仍然练习",
    ru: "Всё равно потренироваться",
    hi: "फिर भी अभ्यास करें",
    bn: "তবুও অনুশীলন করুন",
    ar: "تدرّب على أي حال",
  },
  practiseBlurb: {
    en: "Nothing is due. Try a scenario you have not seen.",
    fr: "Rien à réviser. Essayez un cas encore jamais vu.",
    es: "No hay repasos. Prueba un caso que no hayas visto.",
    pt: "Nada pendente. Tente um caso que ainda não viu.",
    ja: "予定はありません。まだ見ていない事例に挑戦しましょう。",
    zh: "暂无待复习。试一个你没见过的情景。",
    ru: "Ничего не запланировано. Попробуйте новый случай.",
    hi: "कुछ बाकी नहीं। एक नया परिदृश्य आज़माएँ।",
    bn: "কিছু বাকি নেই। নতুন একটি পরিস্থিতি চেষ্টা করুন।",
    ar: "لا شيء مستحق. جرّب حالة لم ترها بعد.",
  },
  nextReviews: {
    en: "Next reviews",
    fr: "Prochaines révisions",
    es: "Próximos repasos",
    pt: "Próximas revisões",
    ja: "次の復習",
    zh: "接下来的复习",
    ru: "Ближайшие повторения",
    hi: "अगले रिवीज़न",
    bn: "পরবর্তী পুনরাবৃত্তি",
    ar: "المراجعات القادمة",
  },
  nothingScheduled: {
    en: "Nothing scheduled yet",
    fr: "Rien de programmé pour l'instant",
    es: "Nada programado todavía",
    pt: "Nada agendado ainda",
    ja: "まだ予定はありません",
    zh: "暂无安排",
    ru: "Пока ничего не запланировано",
    hi: "अभी कुछ निर्धारित नहीं",
    bn: "এখনো কিছু নির্ধারিত নেই",
    ar: "لا شيء مجدول بعد",
  },
  progress: {
    en: "Progress",
    fr: "Progression",
    es: "Progreso",
    pt: "Progresso",
    ja: "進捗",
    zh: "进度",
    ru: "Прогресс",
    hi: "प्रगति",
    bn: "অগ্রগতি",
    ar: "التقدم",
  },
  mastery: {
    en: "Mastery",
    fr: "Maîtrise",
    es: "Dominio",
    pt: "Domínio",
    ja: "習得度",
    zh: "掌握程度",
    ru: "Освоение",
    hi: "महारत",
    bn: "দক্ষতা",
    ar: "الإتقان",
  },
  calibration: {
    en: "Calibration",
    fr: "Calibrage",
    es: "Calibración",
    pt: "Calibração",
    ja: "自信の精度",
    zh: "自信校准",
    ru: "Калибровка",
    hi: "आत्मविश्वास अंशांकन",
    bn: "আত্মবিশ্বাস যাচাই",
    ar: "معايرة الثقة",
  },
  streak: {
    en: "Streak",
    fr: "Série",
    es: "Racha",
    pt: "Sequência",
    ja: "連続",
    zh: "连续天数",
    ru: "Серия",
    hi: "लगातार",
    bn: "ধারাবাহিক",
    ar: "سلسلة",
  },
  best: {
    en: "Best",
    fr: "Record",
    es: "Mejor",
    pt: "Melhor",
    ja: "最高",
    zh: "最佳",
    ru: "Рекорд",
    hi: "सर्वश्रेष्ठ",
    bn: "সেরা",
    ar: "الأفضل",
  },
  caught: {
    en: "Caught",
    fr: "Repérés",
    es: "Detectadas",
    pt: "Detectadas",
    ja: "見抜いた率",
    zh: "识破率",
    ru: "Замечено",
    hi: "पकड़े गए",
    bn: "ধরা পড়েছে",
    ar: "تم كشفها",
  },
  dueNow: {
    en: "Due now",
    fr: "À réviser",
    es: "Toca repasar",
    pt: "Rever agora",
    ja: "今すぐ復習",
    zh: "现在复习",
    ru: "Пора повторить",
    hi: "अभी रिवीज़न",
    bn: "এখনই পুনরাবৃত্তি",
    ar: "حان وقت المراجعة",
  },
  nothingLearnedYet: {
    en: "Play a lesson to start building your map.",
    fr: "Faites une leçon pour commencer votre carte.",
    es: "Haz una lección para empezar tu mapa.",
    pt: "Faça uma lição para começar o seu mapa.",
    ja: "レッスンを1つ終えると、ここに記録が残ります。",
    zh: "完成一节课，就会开始生成你的图谱。",
    ru: "Пройдите урок, чтобы начать свою карту.",
    hi: "अपना नक्शा बनाना शुरू करने के लिए एक पाठ करें।",
    bn: "আপনার মানচিত্র শুরু করতে একটি পাঠ করুন।",
    ar: "أكمل درسًا لتبدأ خريطتك.",
  },
  sureAndWrong: {
    en: "You were sure, and wrong",
    fr: "Vous étiez sûr, et vous aviez tort",
    es: "Estabas seguro, y te equivocaste",
    pt: "Estava certo disso, e errou",
    ja: "確信して、間違えた項目",
    zh: "你很确定，但答错了",
    ru: "Вы были уверены и ошиблись",
    hi: "आप निश्चित थे, और गलत थे",
    bn: "আপনি নিশ্চিত ছিলেন, এবং ভুল ছিলেন",
    ar: "كنت واثقًا، وكنت مخطئًا",
  },
  back: {
    en: "Back",
    fr: "Retour",
    es: "Volver",
    pt: "Voltar",
    ja: "戻る",
    zh: "返回",
    ru: "Назад",
    hi: "वापस",
    bn: "ফিরে যান",
    ar: "رجوع",
  },
  // The interest chooser: what the learner wants to study. Empty means
  // everything, so the default costs no decision.
  interestsTitle: {
    en: "What do you want to learn?",
    fr: "Que voulez-vous apprendre ?",
    es: "¿Qué quieres aprender?",
    pt: "O que você quer aprender?",
    ja: "何を学びたいですか",
    zh: "你想学什么？",
    ru: "Что вы хотите изучать?",
    hi: "आप क्या सीखना चाहते हैं?",
    bn: "আপনি কী শিখতে চান?",
    ar: "ماذا تريد أن تتعلم؟",
  },
  interestsAll: {
    en: "Everything",
    fr: "Tout",
    es: "Todo",
    pt: "Tudo",
    ja: "すべて",
    zh: "全部",
    ru: "Всё",
    hi: "सब कुछ",
    bn: "সবকিছু",
    ar: "كل شيء",
  },
  // Separator between the two ends of a confidence interval, e.g. "8.4 to 25.1".
  // Chrome rather than content, so it lives here and not in a puzzle.
  rangeTo: {
    en: "to",
    fr: "à",
    es: "a",
    pt: "a",
    ja: "から",
    zh: "至",
    ru: "до",
    hi: "से",
    bn: "থেকে",
    ar: "إلى",
  },
  // A way out of a puzzle back to the home screen (which now carries the whole
  // progress dashboard), offered at the lesson and share beats where the flow ends.
  home: {
    en: "Home",
    fr: "Accueil",
    es: "Inicio",
    pt: "Início",
    ja: "ホーム",
    zh: "主页",
    ru: "Главная",
    hi: "होम",
    bn: "হোম",
    ar: "الرئيسية",
  },
  daily: {
    en: "Daily",
    fr: "Quotidien",
    es: "Diario",
    pt: "Diário",
    ja: "毎日",
    zh: "每日",
    ru: "Ежедневно",
    hi: "रोज़ाना",
    bn: "প্রতিদিন",
    ar: "يومي",
  },
  reasoning: {
    en: "reasoning",
    fr: "raisonnement",
    es: "razonamiento",
    pt: "raciocínio",
    ja: "推論",
    zh: "推理",
    ru: "рассуждение",
    hi: "तर्क",
    bn: "যুক্তি",
    ar: "تفكير منطقي",
  },
  playedToday: {
    en: "Played today",
    fr: "Joué aujourd'hui",
    es: "Jugado hoy",
    pt: "Jogado hoje",
    ja: "本日プレイ済み",
    zh: "今天已玩",
    ru: "Сыграно сегодня",
    hi: "आज खेला",
    bn: "আজ খেলা হয়েছে",
    ar: "لعبت اليوم",
  },
  language: {
    en: "Language",
    fr: "Langue",
    es: "Idioma",
    pt: "Idioma",
    ja: "言語",
    zh: "语言",
    ru: "Язык",
    hi: "भाषा",
    bn: "ভাষা",
    ar: "اللغة",
  },

  // @@NEW_KEYS_START (home landing, dashboard sections, and the Confounder mascot; translated by the i18n pass)
  // The Confounder (mascot voice).
  confounderName: {
    en: "The Confounder",
    fr: "Le Confondeur",
    es: "El Confundidor",
    pt: "O Confundidor",
    ja: "交絡師",
    zh: "混杂精",
    ru: "Конфаундер",
    hi: "मायावी",
    bn: "কনফাউন্ডার",
    ar: "المربك",
  },
  confounderWelcome: {
    en: "New here? Wonderful. I do my finest work on beginners.",
    fr: "Nouveau ici ? Merveilleux. C'est sur les débutants que je fais mes meilleurs tours.",
    es: "¿Nuevo por aquí? Estupendo. Con los principiantes es donde hago mi mejor trabajo.",
    pt: "Novato por aqui? Ótimo. É nos iniciantes que eu dou o meu melhor.",
    ja: "初めまして？上等だ。初心者にこそ、腕が鳴る。",
    zh: "新来的？太好了，我最拿手的把戏专治新手。",
    ru: "Впервые здесь? Замечательно. Лучше всего мне удаются именно новички.",
    hi: "नए हो यहाँ? वाह, बढ़िया है। मेरा सबसे उम्दा हुनर नौसिखियों पर ही चलता है।",
    bn: "নতুন এসেছেন? চমৎকার। নতুনদের উপরেই আমার সেরা ফাঁদগুলো খাটে।",
    ar: "جديد هنا؟ رائع. أروع خدعي مع المبتدئين.",
  },
  confounderAllDone: {
    en: "Every trap spotted, every skill burned. Fine. This round is yours.",
    fr: "Tous les pièges repérés, toutes les compétences gravées. Bon. Cette manche est à vous.",
    es: "Todas las trampas al descubierto, todas las habilidades grabadas. Está bien, esta ronda es tuya.",
    pt: "Todas as armadilhas identificadas, todas as habilidades gravadas. Tudo bem. Esta rodada é sua.",
    ja: "罠は全部見破られ、技も全て完全習得か。いいだろう、今回はお前の勝ちだ。",
    zh: "陷阱全被识破，技能全部烙印。行吧，这一局算你赢。",
    ru: "Все ловушки замечены, все навыки закреплены. Что ж, этот раунд за вами.",
    hi: "हर जाल पकड़ा गया, हर स्किल पक्की हुई। ठीक है। यह दौर तुम्हारा रहा।",
    bn: "সব ফাঁদ ধরা পড়েছে, সব দক্ষতা স্থায়ী হয়ে গেছে। ঠিক আছে। এই রাউন্ড আপনার।",
    ar: "كل فخ كُشِف، وكل مهارة ترسّخت. لا بأس، هذه الجولة لك.",
  },
  confounderDue: {
    en: "{n} traps are waiting, and I laid every one of them. Come along.",
    fr: "{n} pièges vous attendent, et c'est moi qui les ai tous posés. Allons-y.",
    es: "{n} trampas te esperan, y las tendí yo, cada una. Vamos.",
    pt: "{n} armadilhas à espera, e fui eu quem armou todas elas. Vamos lá.",
    ja: "{n}件の罠が待っている。全部私が仕込んだものだ。さあ、おいで。",
    zh: "{n}个陷阱正等着你，个个都是我亲手布下的。来吧。",
    ru: "Ловушек: {n}. Каждую расставил я сам. Идёмте.",
    hi: "{n} जाल इंतज़ार में हैं, और हर एक मैंने ही बिछाया है। चलो भी।",
    bn: "{n}টি ফাঁদ অপেক্ষা করছে, আর সবগুলোই আমার পাতা। চলে আসুন।",
    ar: "الفخاخ في انتظارك: {n}، وقد نصبتُها كلّها بنفسي. هيا بنا.",
  },
  confounderMisconceived: {
    en: "You were so certain last time, and so wrong. That one is my favourite.",
    fr: "Vous étiez si sûr de vous la dernière fois, et si loin du compte. Celui-là, c'est mon préféré.",
    es: "La última vez estabas tan seguro, y tan equivocado. Esa es mi favorita.",
    pt: "Da última vez você estava tão certo, e tão errado. Essa é a minha favorita.",
    ja: "前回はやけに自信満々で、盛大に外したな。あれは私のお気に入りだ。",
    zh: "你上次那么笃定，又那么离谱。那道题，是我的最爱。",
    ru: "В прошлый раз вы были так уверены и так ошибались. Это мой любимый случай.",
    hi: "पिछली बार तुम इतने पक्के थे, और उतने ही गलत। वह वाला मेरा पसंदीदा है।",
    bn: "গতবার আপনি এতটাই নিশ্চিত ছিলেন, আর এতটাই ভুল। ওটাই আমার প্রিয়।",
    ar: "كنت واثقًا جدًا في المرة الماضية، ومخطئًا تمامًا. تلك خدعتي المفضّلة.",
  },
  confounderHighCatch: {
    en: "You keep catching me. Frankly, it is getting embarrassing.",
    fr: "Vous n'arrêtez pas de me démasquer. Franchement, ça devient gênant.",
    es: "Me sigues atrapando. Francamente, esto empieza a ser bochornoso.",
    pt: "Você não para de me pegar. Francamente, isso já está ficando constrangedor.",
    ja: "近頃はやけに私を見抜くじゃないか。正直、少々きまりが悪い。",
    zh: "你老是拆穿我。说实话，有点难堪了。",
    ru: "Вы то и дело меня подлавливаете. Откровенно говоря, это уже неловко.",
    hi: "तुम बार-बार मुझे पकड़ लेते हो। सच कहूँ तो, अब शर्मिंदगी होने लगी है।",
    bn: "আপনি ক্রমাগত আমাকে ধরে ফেলছেন। সত্যি বলতে, এটা লজ্জাজনক হয়ে উঠছে।",
    ar: "ما زلت تكشفني مرارًا. بصراحة، الأمر صار محرجًا.",
  },
  confounderStreak: {
    en: "{n} days running. You are becoming genuinely hard to fool.",
    fr: "{n} jours d'affilée. Vous devenez vraiment difficile à berner.",
    es: "{n} días seguidos. Te estás volviendo realmente difícil de engañar.",
    pt: "{n} dias seguidos. Você está ficando realmente difícil de enganar.",
    ja: "{n}日連続か。お前を騙すのが、本当に難しくなってきた。",
    zh: "连续{n}天了，你是真的越来越难骗了。",
    ru: "Дней подряд: {n}. Вас и правда становится всё труднее провести.",
    hi: "{n} दिन लगातार। अब तुम्हें बहकाना सच में मुश्किल होता जा रहा है।",
    bn: "টানা {n} দিন। আপনাকে বোকা বানানো এখন সত্যিই কঠিন হয়ে যাচ্ছে।",
    ar: "أيام متتالية: {n}، وصرت فعلًا يصعب خداعك.",
  },
  confounderBurned: {
    en: "You burned one for good. I will pretend that does not sting.",
    fr: "Vous en avez gravé un pour de bon. Je vais faire comme si ça ne me piquait pas.",
    es: "Grabaste una para siempre. Haré como si no me doliera.",
    pt: "Você gravou uma de vez. Vou fingir que isso não doeu.",
    ja: "また一つ完全習得したか。堪えていないふりをしておこう。",
    zh: "你把一个彻底烙印了，我就假装这不疼吧。",
    ru: "Один навык закреплён навсегда. Сделаю вид, что мне не больно.",
    hi: "तुमने एक को हमेशा के लिए पक्का कर दिया। मैं ऐसा दिखाऊँगा जैसे इससे कुछ चुभा ही नहीं।",
    bn: "একটাকে একেবারে স্থায়ী করে ফেললেন। আমি ভান করব যে এতে আমার গায়ে লাগেনি।",
    ar: "رسّخت مهارة واحدة إلى الأبد. سأتظاهر بأن ذلك لا يؤلمني.",
  },
  confounderIdle: {
    en: "Nothing due just now. Practise anyway, or I shall get ideas.",
    fr: "Rien à réviser pour l'instant. Entraînez-vous quand même, ou je vais avoir des idées.",
    es: "Nada pendiente por ahora. Practica igualmente, o se me ocurrirán ideas.",
    pt: "Nada pendente agora. Pratique mesmo assim, ou vou acabar tendo ideias.",
    ja: "今のところ復習の予定はなし。それでも練習しておけ、暇な私が何か企む前にな。",
    zh: "眼下没有待复习的。还是练一练吧，不然我可要打主意了。",
    ru: "Сейчас ничего не запланировано. Потренируйтесь всё равно, а то у меня появятся идеи.",
    hi: "अभी कुछ बाकी नहीं। फिर भी अभ्यास करो, वरना मैं कुछ नई तरकीबें सोचने लगूँगा।",
    bn: "এখন কিছু বাকি নেই। তবুও অনুশীলন করুন, নইলে আমার মাথায় নতুন ফন্দি আসবে।",
    ar: "لا شيء مستحق الآن. تدرّب على أي حال، وإلا راودتني الأفكار.",
  },
  // Home / About landing.
  aboutLink: {
    en: "About",
    fr: "À propos",
    es: "Acerca de",
    pt: "Sobre",
    ja: "概要",
    zh: "关于",
    ru: "О проекте",
    hi: "परिचय",
    bn: "সম্পর্কে",
    ar: "حول",
  },
  aboutTagline: {
    en: "Get fooled. Then shown the trick.",
    fr: "Laissez-vous piéger. Puis découvrez l'astuce.",
    es: "Déjate engañar. Luego, descubre el truco.",
    pt: "Seja enganado. Depois veja o truque.",
    ja: "騙される。そして、種明かしされる。",
    zh: "先被骗，再拆穿把戏。",
    ru: "Позвольте себя обмануть. Потом мы покажем, в чём фокус.",
    hi: "पहले धोखा खाएँ, फिर तरकीब जानें।",
    bn: "ঠকে যান। তারপর কৌশলটা দেখুন।",
    ar: "انخدع أولًا، ثم اكتشف الخدعة.",
  },
  aboutGoalTitle: {
    en: "What this is",
    fr: "Ce que c'est",
    es: "Qué es esto",
    pt: "O que é isto",
    ja: "これは何か",
    zh: "这是什么",
    ru: "Что это такое",
    hi: "यह क्या है",
    bn: "এটা আসলে কী",
    ar: "ما هذا التطبيق",
  },
  aboutGoalBody: {
    en: "A daily puzzle that teaches you to reason like a scientist. Each one fools you on purpose, then shows you exactly how, so the same trick stops working on you.",
    fr: "Une énigme quotidienne qui vous apprend à raisonner comme un scientifique. Chacune vous piège exprès, puis vous montre exactement comment, pour que le même tour ne fonctionne plus sur vous.",
    es: "Un puzle diario que te enseña a razonar como un científico. Cada uno te engaña a propósito, y luego te muestra exactamente cómo, para que el mismo truco deje de funcionar contigo.",
    pt: "Um desafio diário que ensina você a raciocinar como um cientista. Cada um o engana de propósito, depois mostra exatamente como, para que o mesmo truque nunca mais funcione com você.",
    ja: "毎日出題されるパズルで、科学者のように考える力を養います。どの問題もわざとあなたを騙し、その手口を正確に明かすので、同じ罠には二度と引っかからなくなります。",
    zh: "一道每日谜题，教你像科学家一样推理。每一题都故意误导你，再准确告诉你是怎么被误导的，这样同样的手法就再也骗不了你。",
    ru: "Ежедневная головоломка, которая учит рассуждать как учёный. Каждая нарочно вводит вас в заблуждение, а затем показывает, как именно, чтобы этот трюк больше на вас не действовал.",
    hi: "एक रोज़ाना पहेली जो आपको वैज्ञानिक की तरह सोचना सिखाती है। हर पहेली जानबूझकर आपको धोखा देती है, फिर ठीक-ठीक दिखाती है कि कैसे, ताकि वही तरकीब आप पर दोबारा न चले।",
    bn: "একটি দৈনিক ধাঁধা যা আপনাকে বিজ্ঞানীর মতো যুক্তি করতে শেখায়। প্রতিটি ধাঁধা ইচ্ছাকৃতভাবে আপনাকে ঠকায়, তারপর ঠিক কীভাবে তা ঘটল দেখায়, যাতে একই কৌশল আর আপনার উপর কাজ না করে।",
    ar: "لغز يومي يعلّمك التفكير كعالِم. كل لغز يخدعك عمدًا، ثم يوضح لك كيف بالضبط، حتى لا تنطلي عليك الخدعة نفسها مرة أخرى.",
  },
  aboutHowTitle: {
    en: "How it works",
    fr: "Comment ça marche",
    es: "Cómo funciona",
    pt: "Como funciona",
    ja: "仕組み",
    zh: "运作方式",
    ru: "Как это работает",
    hi: "यह कैसे काम करता है",
    bn: "এটা যেভাবে কাজ করে",
    ar: "كيف يعمل",
  },
  aboutHowSetup: {
    en: "Read a real situation and commit to an answer. No peeking.",
    fr: "Lisez une situation réelle et engagez-vous sur une réponse. Interdit de tricher.",
    es: "Lee una situación real y confirma tu respuesta. Nada de espiar.",
    pt: "Leia uma situação real e escolha uma resposta. Nada de espiar.",
    ja: "実際の状況を読んで、答えを決めます。先読みは禁止です。",
    zh: "阅读一个真实情景，先给出答案，不许偷看。",
    ru: "Прочитайте реальную ситуацию и дайте ответ. Подглядывать нельзя.",
    hi: "एक असली स्थिति पढ़ें, और अपना जवाब पक्का करें। झाँकना नहीं।",
    bn: "একটি বাস্তব পরিস্থিতি পড়ুন এবং একটি উত্তরে স্থির হোন। উঁকি দেওয়া চলবে না।",
    ar: "اقرأ موقفًا حقيقيًا، والتزم بإجابة، من دون غش.",
  },
  aboutHowReveal: {
    en: "See the reveal: the very same data, shown honestly. Most people are wrong, and it stings a little.",
    fr: "Découvrez la révélation : les mêmes données, montrées honnêtement. La plupart des gens se trompent, et ça pique un peu.",
    es: "Mira la revelación: los mismos datos, mostrados con honestidad. La mayoría se equivoca, y escuece un poco.",
    pt: "Veja a revelação: os mesmos dados, mostrados com honestidade. A maioria erra, e dói um pouco.",
    ja: "種明かしを見ます。同じデータを、今度は正直に示します。ほとんどの人は外れて、少し痛い思いをします。",
    zh: "看揭晓：同一组数据，如实呈现。大多数人都会答错，多少有点扎心。",
    ru: "Затем разгадка: те же самые данные, но показанные честно. Большинство ошибается, и это немного задевает.",
    hi: "खुलासा देखें: वही डेटा, पर ईमानदारी से दिखाया गया। ज़्यादातर लोग गलत होते हैं, और थोड़ा चुभता भी है।",
    bn: "উন্মোচনটি দেখুন, একই তথ্য সততার সঙ্গে দেখানো হয়েছে। বেশিরভাগ মানুষই ভুল করেন, আর এটা একটু লাগে।",
    ar: "شاهد الكشف: البيانات نفسها، معروضة بصدق هذه المرة. معظم الناس يخطئون، والأمر يؤلم قليلًا.",
  },
  aboutHowLesson: {
    en: "Keep the lesson, and a card you can send to settle an argument.",
    fr: "Gardez la leçon, et une carte à envoyer pour trancher un débat.",
    es: "Quédate con la lección, y una tarjeta que puedes enviar para zanjar una discusión.",
    pt: "Fique com a lição, e um cartão que você pode enviar para encerrar uma discussão.",
    ja: "レッスンを持ち帰り、議論の決め手になるカードも手に入れましょう。",
    zh: "留下这节课的要点，还有一张可以发出去平息争论的卡片。",
    ru: "Сохраните урок, а с ним карточку, которую можно отправить, чтобы закрыть спор.",
    hi: "पाठ अपने पास रखें, साथ ही एक कार्ड भी जिसे भेजकर बहस खत्म कर सकें।",
    bn: "পাঠটি নিজের কাছে রাখুন, সঙ্গে এমন একটি কার্ড যা কোনো তর্ক মেটাতে পাঠাতে পারবেন।",
    ar: "احتفظ بالدرس، وببطاقة يمكنك إرسالها لحسم نقاش.",
  },
  aboutWhoTitle: {
    en: "Who it is for",
    fr: "Pour qui",
    es: "Para quién es",
    pt: "Para quem é",
    ja: "向いている人",
    zh: "适合谁",
    ru: "Для кого это",
    hi: "यह किसके लिए है",
    bn: "এটা কাদের জন্য",
    ar: "لمن هذا",
  },
  aboutWhoEveryday: {
    en: "Anyone who meets numbers in the news, a chart in an argument, or a claim that sounds too clean.",
    fr: "Quiconque croise des chiffres dans l'actualité, un graphique dans une dispute, ou une affirmation trop belle pour être vraie.",
    es: "Cualquiera que se tope con números en las noticias, un gráfico en una discusión, o una afirmación que suena demasiado perfecta.",
    pt: "Qualquer pessoa que encontre números nas notícias, um gráfico em uma discussão, ou uma afirmação boa demais para ser verdade.",
    ja: "ニュースの数字や、議論に出てくるグラフや、出来すぎた主張に出会う、すべての人へ。",
    zh: "任何在新闻里见过数字、在争论中见过图表，或听过一个说得太漂亮的说法的人。",
    ru: "Для тех, кто сталкивается с цифрами в новостях, графиком в споре или утверждением, звучащим слишком гладко.",
    hi: "कोई भी जो खबरों में आंकड़े, बहस में कोई चार्ट, या बहुत सफाई से कहा गया दावा देखता हो।",
    bn: "যে কেউ, যিনি খবরে সংখ্যা দেখেন, তর্কে কোনো চার্ট দেখেন, বা এমন কোনো দাবি শোনেন যা শুনতে বড্ড মসৃণ লাগে।",
    ar: "أي شخص يصادف أرقامًا في الأخبار، أو رسمًا بيانيًا في نقاش، أو ادّعاءً يبدو مثاليًا أكثر من اللازم.",
  },
  aboutWhoClinical: {
    en: "Students and clinicians who want exam-grade rigor, with every figure traced to a primary source.",
    fr: "Étudiants et cliniciens en quête d'une rigueur digne d'un examen, chaque chiffre étant retracé jusqu'à sa source primaire.",
    es: "Estudiantes y clínicos que buscan el rigor de un examen, con cada cifra rastreada hasta su fuente original.",
    pt: "Estudantes e profissionais de saúde que querem rigor de nível acadêmico, com cada número rastreado até a fonte primária.",
    ja: "試験レベルの厳密さを求める学生や臨床家へ。すべての数値は一次資料までたどれます。",
    zh: "追求考试级严谨度的学生和临床医生，每个数字都能追溯到原始文献。",
    ru: "Для студентов и врачей, которым нужна строгость экзаменационного уровня: каждая цифра прослежена до первоисточника.",
    hi: "वे छात्र और चिकित्सक जिन्हें परीक्षा-स्तर की सटीकता चाहिए, जहाँ हर आंकड़ा मूल स्रोत तक जाँचा गया हो।",
    bn: "যেসব শিক্ষার্থী ও চিকিৎসক পরীক্ষার মানের যথার্থতা চান, যেখানে প্রতিটি সংখ্যা মূল উৎস পর্যন্ত যাচাই করা হয়।",
    ar: "الطلاب والأطباء الذين يريدون دقة بمستوى الامتحانات، مع تتبّع كل رقم إلى مصدره الأساسي.",
  },
  aboutWhyTitle: {
    en: "Why you can trust it",
    fr: "Pourquoi lui faire confiance",
    es: "Por qué puedes confiar en esto",
    pt: "Por que você pode confiar",
    ja: "信頼できる理由",
    zh: "为什么值得信任",
    ru: "Почему этому можно доверять",
    hi: "आप इस पर भरोसा क्यों कर सकते हैं",
    bn: "কেন এটা বিশ্বাস করা যায়",
    ar: "لماذا يمكنك الوثوق به",
  },
  aboutWhyCited: {
    en: "Every number is taken from primary research, read off the table and checked. No hand-waving.",
    fr: "Chaque chiffre provient d'une recherche primaire, relevé directement dans les tableaux et vérifié. Aucune approximation.",
    es: "Cada número procede de investigación original, leído directamente de la tabla y verificado. Nada de vaguedades.",
    pt: "Cada número vem de pesquisa primária, lido direto da tabela e verificado. Sem enrolação.",
    ja: "すべての数字は一次研究の表から直接読み取り、確認済みです。ごまかしはありません。",
    zh: "每个数字都取自原始研究，从表格中核对而来，绝不含糊其辞。",
    ru: "Каждое число взято из оригинального исследования, снято прямо с таблицы и проверено. Никаких голословных утверждений.",
    hi: "हर आंकड़ा मूल शोध से लिया गया है, तालिका से पढ़ा और जाँचा गया है। कोई लाग-लपेट नहीं।",
    bn: "প্রতিটি সংখ্যা মূল গবেষণা থেকে নেওয়া, টেবিল থেকে পড়া এবং যাচাই করা। কোনো আন্দাজে বলা নেই।",
    ar: "كل رقم مأخوذ من بحث أصلي، مقروء من الجدول ومُدقَّق. بلا كلام فارغ.",
  },
  aboutWhyFree: {
    en: "Free, for individuals, for good.",
    fr: "Gratuit, pour les particuliers, pour de bon.",
    es: "Gratis, para particulares, para siempre.",
    pt: "Gratuito, para indivíduos, para sempre.",
    ja: "個人利用は、ずっと無料です。",
    zh: "对个人用户永久免费。",
    ru: "Бесплатно, для частных лиц, навсегда.",
    hi: "व्यक्तिगत उपयोग के लिए, हमेशा के लिए, मुफ़्त।",
    bn: "বিনামূল্যে, ব্যক্তিদের জন্য, চিরকালের জন্য।",
    ar: "مجاني للأفراد، وسيبقى كذلك دائمًا.",
  },
  aboutWhyPrivate: {
    en: "No ads and no tracking. Your answers, streaks and scores never leave your device.",
    fr: "Pas de publicité, pas de suivi. Vos réponses, séries et scores ne quittent jamais votre appareil.",
    es: "Sin anuncios y sin rastreo. Tus respuestas, rachas y puntuaciones nunca salen de tu dispositivo.",
    pt: "Sem anúncios e sem rastreamento. Suas respostas, sequências e pontuações nunca saem do seu dispositivo.",
    ja: "広告も追跡もありません。あなたの回答、連続記録、スコアは端末の外に出ません。",
    zh: "无广告，无追踪。你的答案、连续天数和分数从不离开你的设备。",
    ru: "Никакой рекламы и слежки. Ваши ответы, серии и результаты никогда не покидают устройство.",
    hi: "न विज्ञापन, न ट्रैकिंग। आपके जवाब, लगातार दिन और स्कोर कभी आपकी डिवाइस से बाहर नहीं जाते।",
    bn: "কোনো বিজ্ঞাপন নেই, কোনো ট্র্যাকিং নেই। আপনার উত্তর, ধারাবাহিক ও স্কোর কখনও আপনার ডিভাইস ছেড়ে যায় না।",
    ar: "بلا إعلانات وبلا تتبّع. إجاباتك وسلاسلك ونتائجك لا تغادر جهازك أبدًا.",
  },
  aboutWhyOffline: {
    en: "Works offline once loaded, and installs like an app.",
    fr: "Fonctionne hors ligne une fois chargé, et s'installe comme une application.",
    es: "Funciona sin conexión una vez cargada, y se instala como una aplicación.",
    pt: "Funciona offline depois de carregado, e se instala como um aplicativo.",
    ja: "一度読み込めばオフラインでも使え、アプリのようにインストールできます。",
    zh: "加载一次即可离线使用，还能像应用一样安装。",
    ru: "После загрузки работает офлайн и устанавливается как обычное приложение.",
    hi: "एक बार लोड होने पर ऑफ़लाइन भी काम करता है, और ऐप की तरह इंस्टॉल होता है।",
    bn: "একবার লোড হলে অফলাইনেও কাজ করে, আর অ্যাপের মতোই ইনস্টল করা যায়।",
    ar: "يعمل دون اتصال بعد التحميل الأول، ويُثبَّت مثل أي تطبيق.",
  },
  aboutSeeLesson: {
    en: "See a finished lesson, sources and all",
    fr: "Voir une leçon terminée, sources comprises",
    es: "Mira una lección terminada, con sus fuentes incluidas",
    pt: "Veja uma lição pronta, com fontes e tudo",
    ja: "出典も含め、完成したレッスンを見る",
    zh: "看一节完整的课程，连同全部来源",
    ru: "Посмотреть готовый урок со всеми источниками",
    hi: "एक पूरा पाठ देखें, स्रोतों समेत।",
    bn: "সম্পূর্ণ একটি পাঠ দেখুন, সব উৎসসহ",
    ar: "شاهد درسًا مكتملًا، بمصادره كاملة",
  },
  aboutCta: {
    en: "Play today's puzzle",
    fr: "Jouer à l'énigme du jour",
    es: "Juega el puzle de hoy",
    pt: "Jogar o desafio de hoje",
    ja: "今日のパズルに挑戦",
    zh: "开始今日谜题",
    ru: "Играть в сегодняшнюю головоломку",
    hi: "आज की पहेली खेलें",
    bn: "আজকের ধাঁধাটি খেলুন",
    ar: "العب لغز اليوم",
  },
  // Dashboard (new sections).
  weekAhead: {
    en: "The week ahead",
    fr: "La semaine à venir",
    es: "La semana que viene",
    pt: "A semana que vem",
    ja: "今週の予定",
    zh: "未来一周",
    ru: "Неделя впереди",
    hi: "आने वाला हफ़्ता",
    bn: "আগামী সপ্তাহ",
    ar: "الأسبوع القادم",
  },
  activityTitle: {
    en: "Your turning up",
    fr: "Votre assiduité",
    es: "Tu constancia",
    pt: "Sua constância",
    ja: "あなたの取り組み",
    zh: "你的打卡",
    ru: "Ваша регулярность",
    hi: "आपकी हाज़िरी",
    bn: "আপনার হাজিরা",
    ar: "مواظبتك",
  },
  nemesesTitle: {
    en: "Your nemeses",
    fr: "Vos némésis",
    es: "Tus némesis",
    pt: "Seus arqui-inimigos",
    ja: "あなたの天敵",
    zh: "你的宿敌",
    ru: "Ваши злейшие враги",
    hi: "आपके प्रतिद्वंद्वी",
    bn: "আপনার যম",
    ar: "ألد خصومك",
  },
  nemesesBlurb: {
    en: "The traps that keep catching you. Hunt them down.",
    fr: "Les pièges qui vous prennent sans cesse. Traquez-les.",
    es: "Las trampas que te siguen atrapando. Cázalas.",
    pt: "As armadilhas que sempre pegam você. Cace-as.",
    ja: "何度も引っかかる罠です。狩り出しましょう。",
    zh: "总是让你中招的陷阱，去把它们揪出来。",
    ru: "Ловушки, которые снова и снова вас ловят. Выследите их.",
    hi: "वे जाल जो बार-बार आपको फँसाते हैं। उन्हें ढूँढ निकालें।",
    bn: "যেসব ফাঁদ বারবার আপনাকে ধরে ফেলে। ওগুলোকে খুঁজে বের করুন।",
    ar: "الفخاخ التي لا تزال تُوقعك. طاردها واصطدها.",
  },
  nemesesNone: {
    en: "No nemeses. The Confounder is sulking.",
    fr: "Aucune némésis. Le Confondeur boude.",
    es: "Sin némesis. El Confundidor está enfurruñado.",
    pt: "Nenhum arqui-inimigo. O Confundidor está emburrado.",
    ja: "天敵なし。交絡師はすねています。",
    zh: "没有宿敌，混杂精正在生闷气。",
    ru: "Врагов нет. Конфаундер дуется.",
    hi: "कोई प्रतिद्वंद्वी नहीं। मायावी मुँह फुलाए बैठा है।",
    bn: "কোনো যম নেই। কনফাউন্ডার গোমড়া মুখে বসে আছে।",
    ar: "لا خصوم الآن. المربك عابس.",
  },
  conquestsTitle: {
    en: "Conquered",
    fr: "Conquis",
    es: "Conquistadas",
    pt: "Conquistadas",
    ja: "制覇",
    zh: "已征服",
    ru: "Побеждено",
    hi: "विजय",
    bn: "জয় করা",
    ar: "الانتصارات",
  },
  conquestsBlurb: {
    en: "Burned for good. These no longer fool you.",
    fr: "Gravés pour de bon. Ceux-là ne vous trompent plus.",
    es: "Grabadas para siempre. Estas ya no te engañan.",
    pt: "Gravadas de vez. Elas não enganam mais você.",
    ja: "完全習得済み。もう二度と騙されません。",
    zh: "已被彻底烙印，这些再也骗不了你。",
    ru: "Закреплено навсегда. Эти трюки вас больше не обманут.",
    hi: "हमेशा के लिए पक्का। ये अब आपको धोखा नहीं दे सकते।",
    bn: "একেবারে স্থায়ী হয়ে গেছে। এগুলো আর আপনাকে ঠকাতে পারবে না।",
    ar: "رسّختها إلى الأبد. لم تعد تخدعك.",
  },
  // Lessons browsing (Learn now, search, category filter).
  learnNow: {
    en: "Learn now",
    fr: "Apprendre",
    es: "Aprender ahora",
    pt: "Aprender agora",
    ja: "今すぐ学ぶ",
    zh: "开始学习",
    ru: "Учиться",
    hi: "अभी सीखें",
    bn: "এখনই শিখুন",
    ar: "تعلّم الآن",
  },
  searchPlaceholder: {
    en: "Search lessons",
    fr: "Rechercher une leçon",
    es: "Buscar lecciones",
    pt: "Buscar lições",
    ja: "レッスンを検索",
    zh: "搜索课程",
    ru: "Поиск уроков",
    hi: "पाठ खोजें",
    bn: "পাঠ খুঁজুন",
    ar: "ابحث في الدروس",
  },
  searchNoResults: {
    en: "No lessons match that.",
    fr: "Aucune leçon ne correspond.",
    es: "Ninguna lección coincide.",
    pt: "Nenhuma lição corresponde.",
    ja: "該当するレッスンはありません。",
    zh: "没有匹配的课程。",
    ru: "Нет подходящих уроков.",
    hi: "कोई पाठ मेल नहीं खाता।",
    bn: "কোনো পাঠ মেলে না।",
    ar: "لا توجد دروس مطابقة.",
  },
  categoryAll: {
    en: "All",
    fr: "Toutes",
    es: "Todas",
    pt: "Todas",
    ja: "すべて",
    zh: "全部",
    ru: "Все",
    hi: "सभी",
    bn: "সব",
    ar: "الكل",
  },
  // @@NEW_KEYS_END
};

/**
 * Account panel strings, kept apart from UI only because there are enough of
 * them to be worth their own block. Same rule applies: every locale filled in,
 * enforced by ui.test.ts rather than remembered.
 *
 * The wording is chosen to promise no more than the code does. "Your reviews
 * follow you" is the whole benefit; anything grander would be marketing, and
 * this is a project about not being fooled.
 */
/**
 * The "hand this to someone else" control on the lesson screen. Three strings,
 * kept here rather than inline so ui.test.ts holds them to the same locale
 * parity as everything else.
 */
export const LESSON_SHARE: Record<string, LocalizedText> = {
  blurb: {
    en: "Arguing with someone about this? Send them the explanation.",
    fr: "Vous en discutez avec quelqu'un ? Envoyez-lui l'explication.",
    es: "¿Lo estás discutiendo con alguien? Envíale la explicación.",
    pt: "A discutir isto com alguém? Envie-lhe a explicação.",
    ja: "この件で議論していますか。相手に解説を送れます。",
    zh: "正在和别人争论这个问题？把解释发给对方。",
    ru: "Спорите об этом с кем-то? Отправьте им объяснение.",
    hi: "इस पर किसी से बहस हो रही है? उन्हें समझाने वाला पेज भेजें।",
    bn: "এই নিয়ে কারও সঙ্গে তর্ক চলছে? তাঁকে ব্যাখ্যাটি পাঠান।",
    ar: "تناقش أحدهم في هذا؟ أرسل له الشرح.",
  },
  copy: {
    en: "Copy link",
    fr: "Copier le lien",
    es: "Copiar enlace",
    pt: "Copiar ligação",
    ja: "リンクをコピー",
    zh: "复制链接",
    ru: "Скопировать ссылку",
    hi: "लिंक कॉपी करें",
    bn: "লিঙ্ক কপি করুন",
    ar: "نسخ الرابط",
  },
  copied: {
    en: "Copied",
    fr: "Copié",
    es: "Copiado",
    pt: "Copiado",
    ja: "コピーしました",
    zh: "已复制",
    ru: "Скопировано",
    hi: "कॉपी हो गया",
    bn: "কপি হয়েছে",
    ar: "تم النسخ",
  },
};

export const ACCOUNT: Record<string, LocalizedText> = {
  signIn: {
    en: "Sign in",
    zh: "登录",
    hi: "साइन इन करें",
    es: "Iniciar sesión",
    fr: "Se connecter",
    ar: "تسجيل الدخول",
    bn: "সাইন ইন",
    pt: "Iniciar sessão",
    ru: "Войти",
    ja: "ログイン",
  },
  signedIn: {
    en: "Account",
    zh: "账户",
    hi: "अकाउंट",
    es: "Cuenta",
    fr: "Compte",
    ar: "الحساب",
    bn: "অ্যাকাউন্ট",
    pt: "Conta",
    ru: "Аккаунт",
    ja: "アカウント",
  },
  signedInAs: {
    en: "Signed in as",
    zh: "已登录为",
    hi: "साइन इन किया हुआ अकाउंट",
    es: "Sesión iniciada como",
    fr: "Connecté en tant que",
    ar: "مسجّل الدخول باسم",
    bn: "সাইন ইন করেছেন",
    pt: "Sessão iniciada como",
    ru: "Вы вошли как",
    ja: "ログイン中のアカウント",
  },
  blurb: {
    en: "Optional. An account carries your review schedule between devices, and nothing else.",
    zh: "可选。账户只用于在设备之间同步你的复习计划，不做别的。",
    hi: "वैकल्पिक। अकाउंट आपके रिवीजन शेड्यूल को एक डिवाइस से दूसरे तक ले जाता है, इसके अलावा कुछ नहीं।",
    es: "Opcional. Una cuenta traslada tu calendario de repasos entre dispositivos, y nada más.",
    fr: "Facultatif. Un compte transporte votre programme de révisions d'un appareil à l'autre, et rien de plus.",
    ar: "اختياري. الحساب ينقل جدول مراجعاتك بين أجهزتك، ولا شيء غير ذلك.",
    bn: "ঐচ্ছিক। অ্যাকাউন্ট শুধু আপনার রিভিশনের সময়সূচি এক ডিভাইস থেকে আরেক ডিভাইসে নিয়ে যায়, আর কিছুই নয়।",
    pt: "Opcional. Uma conta leva o teu plano de revisões de um dispositivo para outro, e nada mais.",
    ru: "Необязательно. Аккаунт переносит расписание повторений между устройствами, и больше ничего.",
    ja: "任意です。アカウントは復習スケジュールを端末間で引き継ぐためだけのもので、それ以外には使いません。",
  },
  or: {
    en: "or",
    zh: "或",
    hi: "या",
    es: "o",
    fr: "ou",
    ar: "أو",
    bn: "অথবা",
    pt: "ou",
    ru: "или",
    ja: "または",
  },
  emailLabel: {
    en: "Email address",
    zh: "邮箱地址",
    hi: "ईमेल पता",
    es: "Correo electrónico",
    fr: "Adresse e-mail",
    ar: "البريد الإلكتروني",
    bn: "ইমেইল ঠিকানা",
    pt: "Endereço de email",
    ru: "Электронная почта",
    ja: "メールアドレス",
  },
  emailPlaceholder: {
    en: "you@example.com",
    zh: "you@example.com",
    hi: "you@example.com",
    es: "tu@ejemplo.com",
    fr: "vous@exemple.com",
    ar: "you@example.com",
    bn: "you@example.com",
    pt: "voce@exemplo.com",
    ru: "you@example.com",
    ja: "you@example.com",
  },
  sendCode: {
    en: "Email me a code",
    zh: "发送验证码",
    hi: "मुझे कोड ईमेल करें",
    es: "Enviarme un código",
    fr: "Recevoir un code",
    ar: "أرسل لي رمزًا بالبريد",
    bn: "ইমেইলে কোড পাঠান",
    pt: "Enviar-me um código",
    ru: "Прислать код",
    ja: "コードをメールで送信",
  },
  codeSent: {
    en: "Check your inbox. The code works once and lasts ten minutes.",
    zh: "请查收邮件。验证码只能使用一次，十分钟内有效。",
    hi: "अपना इनबॉक्स देखें। कोड एक ही बार काम करता है और दस मिनट तक चलता है।",
    es: "Revisa tu bandeja de entrada. El código sirve una sola vez y dura diez minutos.",
    fr: "Regardez votre boîte de réception. Le code sert une seule fois et vaut dix minutes.",
    ar: "تفقّد بريدك الوارد. الرمز يعمل مرة واحدة وتنتهي صلاحيته بعد عشر دقائق.",
    bn: "ইনবক্স দেখুন। কোডটি একবারই কাজ করে এবং দশ মিনিট পর্যন্ত বৈধ থাকে।",
    pt: "Vê a tua caixa de entrada. O código serve uma vez e dura dez minutos.",
    ru: "Проверьте почту. Код действует десять минут и только один раз.",
    ja: "受信トレイをご確認ください。コードは1回のみ有効で、10分で失効します。",
  },
  codeLabel: {
    en: "Sign-in code",
    zh: "登录验证码",
    hi: "साइन इन कोड",
    es: "Código de acceso",
    fr: "Code de connexion",
    ar: "رمز تسجيل الدخول",
    bn: "সাইন ইন কোড",
    pt: "Código de acesso",
    ru: "Код входа",
    ja: "ログインコード",
  },
  codePlaceholder: {
    en: "6-digit code",
    zh: "6位验证码",
    hi: "6 अंकों का कोड",
    es: "Código de 6 dígitos",
    fr: "Code à 6 chiffres",
    ar: "رمز من ستة أرقام",
    bn: "৬ সংখ্যার কোড",
    pt: "Código de 6 dígitos",
    ru: "Код из 6 цифр",
    ja: "6桁のコード",
  },
  confirm: {
    en: "Confirm",
    zh: "确认",
    hi: "पुष्टि करें",
    es: "Confirmar",
    fr: "Confirmer",
    ar: "تأكيد",
    bn: "নিশ্চিত করুন",
    pt: "Confirmar",
    ru: "Подтвердить",
    ja: "確認",
  },
  inSync: {
    en: "{n} skills in sync",
    zh: "已同步 {n} 项技能",
    hi: "{n} स्किल सिंक में हैं",
    es: "{n} habilidades sincronizadas",
    fr: "{n} compétences synchronisées",
    ar: "المهارات المتزامنة: {n}",
    bn: "{n}টি দক্ষতা সিঙ্ক করা আছে",
    pt: "{n} competências sincronizadas",
    ru: "Синхронизировано навыков: {n}",
    ja: "{n}件のスキルを同期済み",
  },
  download: {
    en: "Download my data",
    zh: "下载我的数据",
    hi: "मेरा डेटा डाउनलोड करें",
    es: "Descargar mis datos",
    fr: "Télécharger mes données",
    ar: "تنزيل بياناتي",
    bn: "আমার ডেটা ডাউনলোড করুন",
    pt: "Descarregar os meus dados",
    ru: "Скачать мои данные",
    ja: "データをダウンロード",
  },
  signOut: {
    en: "Sign out",
    zh: "退出登录",
    hi: "साइन आउट करें",
    es: "Cerrar sesión",
    fr: "Se déconnecter",
    ar: "تسجيل الخروج",
    bn: "সাইন আউট",
    pt: "Terminar sessão",
    ru: "Выйти",
    ja: "ログアウト",
  },
  delete: {
    en: "Delete my account",
    zh: "删除我的账户",
    hi: "मेरा अकाउंट डिलीट करें",
    es: "Eliminar mi cuenta",
    fr: "Supprimer mon compte",
    ar: "حذف حسابي",
    bn: "অ্যাকাউন্ট মুছে ফেলুন",
    pt: "Eliminar a minha conta",
    ru: "Удалить аккаунт",
    ja: "アカウントを削除",
  },
  deleteWarning: {
    en: "This erases your account and every review it holds, on the server and on this device, immediately. There is no undo and no grace period.",
    zh: "此操作会立即删除你的账户，以及其中的全部复习记录，服务器上和本设备上的都会删除。无法撤销，也没有缓冲期。",
    hi: "इससे आपका अकाउंट और उसमें मौजूद हर रिवीजन, सर्वर पर और इस डिवाइस पर, तुरंत मिट जाता है। यह वापस नहीं लिया जा सकता और कोई मोहलत अवधि नहीं है।",
    es: "Esto borra tu cuenta y todos los repasos que contiene, en el servidor y en este dispositivo, de inmediato. No se puede deshacer y no hay periodo de gracia.",
    fr: "Cela efface immédiatement votre compte et toutes les révisions qu'il contient, sur le serveur et sur cet appareil. Il n'y a aucun retour en arrière et aucun délai de grâce.",
    ar: "هذا يمحو حسابك وكل مراجعة يحتوي عليها، على الخادم وعلى هذا الجهاز، فورًا. لا يمكن التراجع عن ذلك ولا توجد مهلة سماح.",
    bn: "এটি আপনার অ্যাকাউন্ট এবং তাতে থাকা প্রতিটি রিভিশন সার্ভারে ও এই ডিভাইসে সঙ্গে সঙ্গে মুছে ফেলে। এটি ফিরিয়ে আনার কোনো উপায় নেই, এবং অপেক্ষার কোনো সময়ও দেওয়া হয় না।",
    pt: "Isto apaga a tua conta e todas as revisões que ela contém, no servidor e neste dispositivo, de imediato. Não há como anular nem período de espera.",
    ru: "Это немедленно удалит ваш аккаунт и все хранящиеся в нём повторения, и на сервере, и на этом устройстве. Отменить действие нельзя, отсрочки нет.",
    ja: "アカウントと、そこに保存されているすべての復習記録を、サーバー上とこの端末上の両方から直ちに消去します。取り消しはできず、猶予期間もありません。",
  },
  deleteYes: {
    en: "Yes, erase everything",
    zh: "是，全部删除",
    hi: "हाँ, सब कुछ मिटा दें",
    es: "Sí, borrarlo todo",
    fr: "Oui, tout effacer",
    ar: "نعم، امحُ كل شيء",
    bn: "হ্যাঁ, সব মুছে ফেলুন",
    pt: "Sim, apagar tudo",
    ru: "Да, удалить всё",
    ja: "はい、すべて消去します",
  },
  cancel: {
    en: "Keep my account",
    zh: "保留我的账户",
    hi: "मेरा अकाउंट रहने दें",
    es: "Conservar mi cuenta",
    fr: "Garder mon compte",
    ar: "الاحتفاظ بحسابي",
    bn: "অ্যাকাউন্ট রেখে দিন",
    pt: "Manter a conta",
    ru: "Оставить аккаунт",
    ja: "アカウントを残す",
  },
  privacyNote: {
    en: "We store your email address and your review schedule. Nothing else.",
    zh: "我们只保存你的邮箱地址和复习计划，不保存其他内容。",
    hi: "हम आपका ईमेल पता और आपका रिवीजन शेड्यूल स्टोर करते हैं। इसके अलावा कुछ नहीं।",
    es: "Guardamos tu correo electrónico y tu calendario de repasos. Nada más.",
    fr: "Nous conservons votre adresse e-mail et votre programme de révisions. Rien d'autre.",
    ar: "نخزّن بريدك الإلكتروني وجدول مراجعاتك. لا شيء غير ذلك.",
    bn: "আমরা আপনার ইমেইল ঠিকানা এবং রিভিশনের সময়সূচি সংরক্ষণ করি। আর কিছুই নয়।",
    pt: "Guardamos o teu endereço de email e o teu plano de revisões. Nada mais.",
    ru: "Мы храним ваш адрес почты и расписание повторений. Больше ничего.",
    ja: "保存するのはメールアドレスと復習スケジュールのみです。それ以外は保存しません。",
  },
  privacyLink: {
    en: "What we store, and why",
    zh: "我们保存什么，为什么保存",
    hi: "हम क्या स्टोर करते हैं, और क्यों",
    es: "Qué guardamos, y por qué",
    fr: "Ce que nous conservons, et pourquoi",
    ar: "ما الذي نخزّنه ولماذا",
    bn: "আমরা কী সংরক্ষণ করি, এবং কেন",
    pt: "O que guardamos, e porquê",
    ru: "Что мы храним и зачем",
    ja: "保存する情報とその理由",
  },
  errNetwork: {
    en: "No connection. Try again.",
    zh: "无网络连接，请重试。",
    hi: "कनेक्शन नहीं है। फिर कोशिश करें।",
    es: "Sin conexión. Inténtalo de nuevo.",
    fr: "Pas de connexion. Réessayez.",
    ar: "لا يوجد اتصال. حاول مرة أخرى.",
    bn: "সংযোগ নেই। আবার চেষ্টা করুন।",
    pt: "Sem ligação. Tenta de novo.",
    ru: "Нет соединения. Попробуйте снова.",
    ja: "接続できません。もう一度お試しください。",
  },
  errBadEmail: {
    en: "That does not look like an email address.",
    zh: "这看起来不像是邮箱地址。",
    hi: "यह ईमेल पता नहीं लगता।",
    es: "Eso no parece un correo electrónico.",
    fr: "Cela ne ressemble pas à une adresse e-mail.",
    ar: "هذا لا يبدو بريدًا إلكترونيًا.",
    bn: "এটি ইমেইল ঠিকানা বলে মনে হচ্ছে না।",
    pt: "Isto não parece um endereço de email.",
    ru: "Это не похоже на адрес электронной почты.",
    ja: "メールアドレスの形式が正しくないようです。",
  },
  errBadCode: {
    en: "That code is not right.",
    zh: "验证码不正确。",
    hi: "यह कोड सही नहीं है।",
    es: "Ese código no es correcto.",
    fr: "Ce code n'est pas le bon.",
    ar: "هذا الرمز غير صحيح.",
    bn: "কোডটি ঠিক নয়।",
    pt: "Esse código não está correto.",
    ru: "Код неверный.",
    ja: "コードが正しくありません。",
  },
  errTooManyAttempts: {
    en: "Too many tries. Ask for a new code.",
    zh: "尝试次数过多，请重新获取验证码。",
    hi: "बहुत ज़्यादा कोशिशें। नया कोड मंगाएँ।",
    es: "Demasiados intentos. Pide un código nuevo.",
    fr: "Trop de tentatives. Demandez un nouveau code.",
    ar: "محاولات كثيرة. اطلب رمزًا جديدًا.",
    bn: "অনেকবার চেষ্টা করা হয়েছে। নতুন কোড নিন।",
    pt: "Demasiadas tentativas. Pede um código novo.",
    ru: "Слишком много попыток. Запросите новый код.",
    ja: "試行回数が多すぎます。新しいコードを取得してください。",
  },
  errTooManyRequests: {
    en: "Too many requests. Try again later.",
    zh: "请求过于频繁，请稍后再试。",
    hi: "बहुत ज़्यादा अनुरोध। बाद में कोशिश करें।",
    es: "Demasiadas solicitudes. Inténtalo más tarde.",
    fr: "Trop de requêtes. Réessayez plus tard.",
    ar: "طلبات كثيرة. حاول لاحقًا.",
    bn: "অনেক বেশি অনুরোধ। পরে আবার চেষ্টা করুন।",
    pt: "Demasiados pedidos. Tenta mais tarde.",
    ru: "Слишком много запросов. Попробуйте позже.",
    ja: "リクエストが多すぎます。しばらくしてからお試しください。",
  },
  errCodeJustSent: {
    en: "A code just went out. Give it a minute.",
    zh: "验证码刚刚发出，请稍等一分钟。",
    hi: "कोड अभी भेजा गया है। एक मिनट रुकें।",
    es: "Acabamos de enviar un código. Espera un minuto.",
    fr: "Un code vient de partir. Patientez une minute.",
    ar: "أُرسل رمز للتو. انتظر دقيقة.",
    bn: "একটি কোড এইমাত্র পাঠানো হয়েছে। এক মিনিট অপেক্ষা করুন।",
    pt: "Acabou de sair um código. Aguarda um minuto.",
    ru: "Код только что отправлен. Подождите минуту.",
    ja: "コードを送信したばかりです。少しお待ちください。",
  },
  errEmailLinked: {
    en: "That address already belongs to a different Google account.",
    zh: "该地址已属于另一个 Google 账户。",
    hi: "यह पता पहले से किसी दूसरे Google अकाउंट का है।",
    es: "Esa dirección ya pertenece a otra cuenta de Google.",
    fr: "Cette adresse appartient déjà à un autre compte Google.",
    ar: "هذا العنوان مرتبط بحساب Google آخر.",
    bn: "এই ঠিকানাটি অন্য একটি Google অ্যাকাউন্টের সঙ্গে যুক্ত।",
    pt: "Esse endereço já pertence a outra conta Google.",
    ru: "Этот адрес уже привязан к другому аккаунту Google.",
    ja: "このアドレスは別のGoogleアカウントに登録されています。",
  },
  errEmailUnavailable: {
    en: "Email sign-in is not set up here.",
    zh: "此处未启用邮箱登录。",
    hi: "यहाँ ईमेल से साइन इन उपलब्ध नहीं है।",
    es: "El inicio de sesión por correo no está configurado aquí.",
    fr: "La connexion par e-mail n'est pas disponible ici.",
    ar: "تسجيل الدخول بالبريد غير مُفعّل هنا.",
    bn: "এখানে ইমেইল দিয়ে সাইন ইন চালু নেই।",
    pt: "O acesso por email não está configurado aqui.",
    ru: "Вход по почте здесь не настроен.",
    ja: "メールでのログインはご利用いただけません。",
  },
  errGoogleBlocked: {
    en: "Google sign-in could not load. Use the email option instead.",
    zh: "Google 登录无法加载，请改用邮箱方式。",
    hi: "Google साइन इन लोड नहीं हो सका। इसके बजाय ईमेल विकल्प चुनें।",
    es: "No se pudo cargar el acceso con Google. Usa la opción de correo.",
    fr: "La connexion Google n'a pas pu se charger. Utilisez plutôt l'e-mail.",
    ar: "تعذّر تحميل تسجيل الدخول عبر Google. استخدم خيار البريد.",
    bn: "Google সাইন ইন লোড করা যায়নি। এর বদলে ইমেইল ব্যবহার করুন।",
    pt: "Não foi possível carregar o acesso Google. Usa a opção de email.",
    ru: "Вход через Google не загрузился. Воспользуйтесь входом по почте.",
    ja: "Googleログインを読み込めませんでした。メールでのログインをご利用ください。",
  },
  errGeneric: {
    en: "Something went wrong. Try again.",
    zh: "出了点问题，请重试。",
    hi: "कुछ गड़बड़ हो गई। फिर कोशिश करें।",
    es: "Algo salió mal. Inténtalo de nuevo.",
    fr: "Une erreur est survenue. Réessayez.",
    ar: "حدث خطأ ما. حاول مرة أخرى.",
    bn: "কিছু একটা ভুল হয়েছে। আবার চেষ্টা করুন।",
    pt: "Algo correu mal. Tenta de novo.",
    ru: "Что-то пошло не так. Попробуйте снова.",
    ja: "問題が発生しました。もう一度お試しください。",
  },
};
