/**
 * Regenerate AGENTS.md from CLAUDE.md.
 *
 * AGENTS.md exists for tools that read that filename instead of CLAUDE.md. It
 * is a verbatim copy behind a short header, and it is generated rather than
 * maintained, because the hand-maintained version drifted two weeks out of
 * date without anyone noticing: it still described the shape checklist as it
 * stood before the `full` prop and the aria-label rule, and was written in the
 * em-dash style the project had since abandoned. A second copy of the rules
 * that says something different from the first is worse than no second copy.
 *
 * Run `pnpm gen:agents` after editing CLAUDE.md. `src/agentsParity.test.ts`
 * fails if you forget.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = join(root, "CLAUDE.md");
const target = join(root, "AGENTS.md");

export const HEADER = `<!--
  Mirror of CLAUDE.md, for tools that read AGENTS.md instead.

  CLAUDE.md IS THE SOURCE OF TRUTH. Everything below this comment is a verbatim
  copy of it. Do not edit this file by hand: edit CLAUDE.md and run
  \`pnpm gen:agents\`. If the two drift, whichever tool reads this one starts
  working from stale rules, which is exactly what happened to the version of
  this file that preceded the check.

  Generated by scripts/gen-agents.mjs. Enforced by src/agentsParity.test.ts.
-->

`;

const claude = readFileSync(source, "utf8");
const out = HEADER + claude;

writeFileSync(target, out);

// Assert rather than trust: a copy that is not byte-identical is the one
// failure this script exists to prevent.
const written = readFileSync(target, "utf8");
if (!written.endsWith(claude)) throw new Error("AGENTS.md body is not identical to CLAUDE.md");

console.log(`AGENTS.md regenerated: ${written.length} bytes (body ${claude.length}).`);
