import { describe, expect, it } from "vitest";
import agents from "../AGENTS.md?raw";
import claude from "../CLAUDE.md?raw";

/**
 * AGENTS.md must carry CLAUDE.md verbatim.
 *
 * The project keeps its rules in CLAUDE.md, and some tools read AGENTS.md
 * instead. Two files holding the same rules is a duplication the repo can
 * afford; two files holding DIFFERENT rules is the failure this exists to
 * prevent, and it is not hypothetical. The hand-maintained AGENTS.md drifted
 * two weeks: it described the shape checklist as it stood before the `full`
 * prop and before the aria-label rule, and it was written in the em-dash style
 * the project had abandoned. Nothing failed, because nothing was checking, and
 * the file was git-ignored so no reviewer ever saw it in a diff.
 *
 * Tracking it and asserting equality turns "remember to update both" into a
 * red test, which is the same move `coverage.test.ts` and `docsCoverage.test.ts`
 * make for translations and planning docs.
 */
describe("AGENTS.md", () => {
  it("carries CLAUDE.md verbatim, behind its header", () => {
    // A trailing-substring check rather than a diff of the whole file, because
    // the header is the only licensed difference between them.
    expect(agents.endsWith(claude)).toBe(true);
  });

  it("adds only a header, and says where the rules actually live", () => {
    const header = agents.slice(0, agents.length - claude.length);
    expect(header).toContain("CLAUDE.md IS THE SOURCE OF TRUTH");
    expect(header).toContain("pnpm gen:agents");
    // The header must be a comment, or it would read as repository prose and
    // the first heading a tool sees would not be the project's own.
    expect(header.trimStart().startsWith("<!--")).toBe(true);
    expect(header).toContain("-->");
  });

  /**
   * The regeneration path has to be discoverable from the failure, or the next
   * person hand-edits AGENTS.md and drift starts again by a different route.
   */
  it("is regenerated by a script the failure can point at", async () => {
    const scripts = import.meta.glob("../scripts/*.mjs", {
      query: "?raw",
      import: "default",
      eager: true,
    }) as Record<string, string>;
    const gen = Object.entries(scripts).find(([p]) => p.endsWith("gen-agents.mjs"));
    expect(gen).toBeDefined();
    expect(gen![1]).toContain("AGENTS.md");
  });

  /**
   * The house style, applied to the copy as much as to the source.
   *
   * Written as escapes rather than as the characters themselves, so that this
   * file does not trip the very scan it performs. A dash-forbidding test whose
   * matcher is spelled with dashes is its own counterexample.
   */
  it("carries no em or en dashes", () => {
    const DASHES = new RegExp("[\u2014\u2013]");
    expect(DASHES.test(agents)).toBe(false);
  });
});
